// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tri2d_initEnhancedGrid (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        vertex_used_V_address0,
        vertex_used_V_ce0,
        vertex_used_V_q0,
        vertex_x_V_address0,
        vertex_x_V_ce0,
        vertex_x_V_q0,
        vertex_y_V_address0,
        vertex_y_V_ce0,
        vertex_y_V_q0,
        enhanced_grid_x_min_V,
        enhanced_grid_x_min_V_ap_vld,
        enhanced_grid_y_min_V,
        enhanced_grid_y_min_V_ap_vld,
        enhanced_grid_x_max_V,
        enhanced_grid_x_max_V_ap_vld,
        enhanced_grid_y_max_V,
        enhanced_grid_y_max_V_ap_vld,
        enhanced_grid_grid_size_x,
        enhanced_grid_grid_size_x_ap_vld,
        enhanced_grid_grid_size_y,
        enhanced_grid_grid_size_y_ap_vld,
        enhanced_grid_total_cells,
        enhanced_grid_total_cells_ap_vld,
        enhanced_grid_cell_width_V,
        enhanced_grid_cell_width_V_ap_vld,
        enhanced_grid_cell_height_V,
        enhanced_grid_cell_height_V_ap_vld,
        enhanced_grid_flat_cells_triangle_count_address0,
        enhanced_grid_flat_cells_triangle_count_ce0,
        enhanced_grid_flat_cells_triangle_count_we0,
        enhanced_grid_flat_cells_triangle_count_d0,
        grp_fu_1099_p_din0,
        grp_fu_1099_p_dout0,
        grp_fu_1099_p_ce,
        grp_fu_1102_p_din0,
        grp_fu_1102_p_dout0,
        grp_fu_1102_p_ce
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] vertex_used_V_address0;
output   vertex_used_V_ce0;
input  [0:0] vertex_used_V_q0;
output  [12:0] vertex_x_V_address0;
output   vertex_x_V_ce0;
input  [23:0] vertex_x_V_q0;
output  [12:0] vertex_y_V_address0;
output   vertex_y_V_ce0;
input  [23:0] vertex_y_V_q0;
output  [23:0] enhanced_grid_x_min_V;
output   enhanced_grid_x_min_V_ap_vld;
output  [23:0] enhanced_grid_y_min_V;
output   enhanced_grid_y_min_V_ap_vld;
output  [23:0] enhanced_grid_x_max_V;
output   enhanced_grid_x_max_V_ap_vld;
output  [23:0] enhanced_grid_y_max_V;
output   enhanced_grid_y_max_V_ap_vld;
output  [6:0] enhanced_grid_grid_size_x;
output   enhanced_grid_grid_size_x_ap_vld;
output  [6:0] enhanced_grid_grid_size_y;
output   enhanced_grid_grid_size_y_ap_vld;
output  [12:0] enhanced_grid_total_cells;
output   enhanced_grid_total_cells_ap_vld;
output  [23:0] enhanced_grid_cell_width_V;
output   enhanced_grid_cell_width_V_ap_vld;
output  [23:0] enhanced_grid_cell_height_V;
output   enhanced_grid_cell_height_V_ap_vld;
output  [11:0] enhanced_grid_flat_cells_triangle_count_address0;
output   enhanced_grid_flat_cells_triangle_count_ce0;
output   enhanced_grid_flat_cells_triangle_count_we0;
output  [31:0] enhanced_grid_flat_cells_triangle_count_d0;
output  [31:0] grp_fu_1099_p_din0;
input  [63:0] grp_fu_1099_p_dout0;
output   grp_fu_1099_p_ce;
output  [31:0] grp_fu_1102_p_din0;
input  [63:0] grp_fu_1102_p_dout0;
output   grp_fu_1102_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg enhanced_grid_x_min_V_ap_vld;
reg enhanced_grid_y_min_V_ap_vld;
reg enhanced_grid_x_max_V_ap_vld;
reg enhanced_grid_y_max_V_ap_vld;
reg enhanced_grid_grid_size_x_ap_vld;
reg enhanced_grid_grid_size_y_ap_vld;
reg enhanced_grid_total_cells_ap_vld;
reg enhanced_grid_cell_width_V_ap_vld;
reg enhanced_grid_cell_height_V_ap_vld;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [24:0] ret_V_61_fu_324_p2;
reg   [24:0] ret_V_61_reg_1474;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln1090_fu_330_p2;
reg   [0:0] icmp_ln1090_reg_1479;
reg   [0:0] p_Result_53_reg_1484;
wire   [24:0] tmp_V_fu_344_p2;
reg   [24:0] tmp_V_reg_1490;
wire   [24:0] ret_V_62_fu_358_p2;
reg   [24:0] ret_V_62_reg_1495;
wire   [0:0] icmp_ln1090_2_fu_364_p2;
reg   [0:0] icmp_ln1090_2_reg_1500;
reg   [0:0] p_Result_56_reg_1505;
wire   [24:0] tmp_V_7_fu_378_p2;
reg   [24:0] tmp_V_7_reg_1511;
wire   [31:0] LD_fu_656_p1;
reg   [31:0] LD_reg_1516;
wire    ap_CS_fsm_state4;
wire   [31:0] LD_4_fu_932_p1;
reg   [31:0] LD_4_reg_1521;
wire    ap_CS_fsm_state5;
wire   [31:0] grp_fu_172_p2;
reg   [31:0] phitmp_reg_1536;
wire    ap_CS_fsm_state7;
wire   [31:0] grp_fu_177_p2;
reg   [31:0] phitmp1_reg_1541;
wire   [31:0] select_ln1090_fu_944_p3;
reg   [31:0] select_ln1090_reg_1546;
wire    ap_CS_fsm_state8;
wire   [31:0] select_ln1090_1_fu_951_p3;
reg   [31:0] select_ln1090_1_reg_1552;
reg   [0:0] p_Result_59_reg_1558;
wire    ap_CS_fsm_state9;
reg   [10:0] exp_tmp_reg_1563;
wire   [51:0] trunc_ln554_fu_984_p1;
reg   [51:0] trunc_ln554_reg_1568;
wire   [0:0] icmp_ln560_fu_988_p2;
reg   [0:0] icmp_ln560_reg_1573;
reg   [0:0] p_Result_61_reg_1580;
reg   [10:0] exp_tmp_3_reg_1585;
wire   [51:0] trunc_ln554_3_fu_1020_p1;
reg   [51:0] trunc_ln554_3_reg_1590;
wire   [0:0] icmp_ln560_3_fu_1024_p2;
reg   [0:0] icmp_ln560_3_reg_1595;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_start;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_done;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_idle;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_ready;
wire   [23:0] grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out_ap_vld;
wire   [23:0] grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out1;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out1_ap_vld;
wire   [23:0] grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out2;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out2_ap_vld;
wire   [23:0] grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out3;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out3_ap_vld;
wire   [12:0] grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_used_V_address0;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_used_V_ce0;
wire   [12:0] grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_x_V_address0;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_x_V_ce0;
wire   [12:0] grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_y_V_address0;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_y_V_ce0;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_start;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_done;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_idle;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_ready;
wire   [11:0] grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_enhanced_grid_flat_cells_triangle_count_address0;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_enhanced_grid_flat_cells_triangle_count_ce0;
wire    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_enhanced_grid_flat_cells_triangle_count_we0;
wire   [31:0] grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_enhanced_grid_flat_cells_triangle_count_d0;
reg    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_start_reg;
wire  signed [23:0] rhs_fu_258_p2;
wire  signed [23:0] rhs_3_fu_280_p2;
wire  signed [23:0] lhs_V_fu_292_p2;
wire  signed [23:0] lhs_V_3_fu_304_p2;
wire    ap_CS_fsm_state10;
wire   [31:0] grp_fu_172_p0;
wire   [31:0] grp_fu_177_p0;
wire  signed [23:0] sext_ln1348_fu_200_p0;
wire  signed [23:0] sext_ln1348_21_fu_204_p0;
wire  signed [24:0] sext_ln1348_fu_200_p1;
wire  signed [24:0] sext_ln1348_21_fu_204_p1;
wire  signed [24:0] ret_V_fu_208_p2;
wire   [25:0] r_V_45_fu_218_p1;
wire  signed [23:0] sext_ln1348_22_fu_224_p0;
wire  signed [23:0] sext_ln1348_23_fu_228_p0;
wire  signed [24:0] sext_ln1348_22_fu_224_p1;
wire  signed [24:0] sext_ln1348_23_fu_228_p1;
wire  signed [24:0] ret_V_60_fu_232_p2;
wire   [25:0] r_V_47_fu_242_p1;
wire   [50:0] r_V_45_fu_218_p2;
wire  signed [23:0] rhs_fu_258_p0;
wire   [23:0] trunc_ln_fu_248_p4;
wire   [50:0] r_V_47_fu_242_p2;
wire  signed [23:0] rhs_3_fu_280_p0;
wire   [23:0] trunc_ln818_1_fu_270_p4;
wire  signed [23:0] lhs_V_fu_292_p1;
wire  signed [23:0] lhs_V_3_fu_304_p1;
wire  signed [24:0] sext_ln813_fu_316_p1;
wire  signed [24:0] sext_ln813_7_fu_320_p1;
wire  signed [24:0] sext_ln813_8_fu_350_p1;
wire  signed [24:0] sext_ln813_9_fu_354_p1;
wire   [24:0] tmp_V_9_fu_384_p3;
reg   [24:0] p_Result_s_fu_389_p4;
wire   [25:0] p_Result_54_fu_399_p3;
wire  signed [31:0] sext_ln1198_fu_407_p1;
reg   [31:0] l_fu_411_p3;
wire   [31:0] sub_ln1099_fu_419_p2;
wire   [31:0] lsb_index_fu_429_p2;
wire   [30:0] tmp_fu_435_p4;
wire   [4:0] trunc_ln1102_fu_451_p1;
wire   [4:0] sub_ln1102_fu_455_p2;
wire   [24:0] zext_ln1102_fu_461_p1;
wire   [24:0] lshr_ln1102_fu_465_p2;
wire   [24:0] p_Result_38_fu_471_p2;
wire   [0:0] icmp_ln1101_fu_445_p2;
wire   [0:0] icmp_ln1102_fu_477_p2;
wire   [0:0] tmp_24_fu_489_p3;
wire   [24:0] trunc_ln1099_fu_425_p1;
wire   [24:0] add_ln1104_fu_503_p2;
wire   [0:0] p_Result_39_fu_509_p3;
wire   [0:0] xor_ln1104_fu_497_p2;
wire   [0:0] and_ln1104_fu_517_p2;
wire   [0:0] a_fu_483_p2;
wire   [0:0] or_ln1104_3_fu_523_p2;
wire   [31:0] add_ln1113_fu_547_p2;
wire   [63:0] zext_ln1112_fu_537_p1;
wire   [63:0] zext_ln1113_fu_553_p1;
wire   [63:0] zext_ln1114_fu_563_p1;
wire   [0:0] icmp_ln1113_fu_541_p2;
wire   [63:0] lshr_ln1113_fu_557_p2;
wire   [63:0] shl_ln1114_fu_567_p2;
wire   [1:0] or_ln_fu_529_p3;
wire   [63:0] m_7_fu_573_p3;
wire   [63:0] zext_ln1116_fu_581_p1;
wire   [63:0] m_8_fu_585_p2;
wire   [62:0] m_14_fu_591_p4;
wire   [0:0] p_Result_40_fu_605_p3;
wire   [7:0] trunc_ln1098_fu_621_p1;
wire   [7:0] sub_ln1119_fu_625_p2;
wire   [7:0] select_ln1098_fu_613_p3;
wire   [7:0] add_ln1124_fu_631_p2;
wire   [63:0] zext_ln1117_fu_601_p1;
wire   [8:0] tmp_3_fu_637_p3;
wire   [63:0] p_Result_55_fu_644_p5;
wire   [24:0] tmp_V_10_fu_660_p3;
reg   [24:0] p_Result_43_fu_665_p4;
wire   [25:0] p_Result_57_fu_675_p3;
wire  signed [31:0] sext_ln1198_1_fu_683_p1;
reg   [31:0] l_2_fu_687_p3;
wire   [31:0] sub_ln1099_2_fu_695_p2;
wire   [31:0] lsb_index_2_fu_705_p2;
wire   [30:0] tmp_27_fu_711_p4;
wire   [4:0] trunc_ln1102_2_fu_727_p1;
wire   [4:0] sub_ln1102_2_fu_731_p2;
wire   [24:0] zext_ln1102_2_fu_737_p1;
wire   [24:0] lshr_ln1102_2_fu_741_p2;
wire   [24:0] p_Result_45_fu_747_p2;
wire   [0:0] icmp_ln1101_2_fu_721_p2;
wire   [0:0] icmp_ln1102_2_fu_753_p2;
wire   [0:0] tmp_28_fu_765_p3;
wire   [24:0] trunc_ln1099_1_fu_701_p1;
wire   [24:0] add_ln1104_1_fu_779_p2;
wire   [0:0] p_Result_46_fu_785_p3;
wire   [0:0] xor_ln1104_2_fu_773_p2;
wire   [0:0] and_ln1104_2_fu_793_p2;
wire   [0:0] a_2_fu_759_p2;
wire   [0:0] or_ln1104_fu_799_p2;
wire   [31:0] add_ln1113_1_fu_823_p2;
wire   [63:0] zext_ln1112_1_fu_813_p1;
wire   [63:0] zext_ln1113_1_fu_829_p1;
wire   [63:0] zext_ln1114_1_fu_839_p1;
wire   [0:0] icmp_ln1113_1_fu_817_p2;
wire   [63:0] lshr_ln1113_1_fu_833_p2;
wire   [63:0] shl_ln1114_1_fu_843_p2;
wire   [1:0] or_ln1104_2_fu_805_p3;
wire   [63:0] m_10_fu_849_p3;
wire   [63:0] zext_ln1116_2_fu_857_p1;
wire   [63:0] m_11_fu_861_p2;
wire   [62:0] m_fu_867_p4;
wire   [0:0] p_Result_47_fu_881_p3;
wire   [7:0] trunc_ln1098_2_fu_897_p1;
wire   [7:0] sub_ln1119_2_fu_901_p2;
wire   [7:0] select_ln1098_2_fu_889_p3;
wire   [7:0] add_ln1124_2_fu_907_p2;
wire   [63:0] zext_ln1117_1_fu_877_p1;
wire   [8:0] tmp_4_fu_913_p3;
wire   [63:0] p_Result_58_fu_920_p5;
wire   [63:0] ireg_fu_958_p1;
wire   [62:0] trunc_ln544_fu_962_p1;
wire   [63:0] ireg_3_fu_994_p1;
wire   [62:0] trunc_ln544_3_fu_998_p1;
wire   [52:0] p_Result_60_fu_1051_p3;
wire   [53:0] zext_ln558_fu_1058_p1;
wire   [53:0] man_V_11_fu_1062_p2;
wire   [11:0] zext_ln455_fu_1048_p1;
wire   [11:0] F2_fu_1075_p2;
wire   [0:0] icmp_ln570_fu_1081_p2;
wire   [11:0] add_ln570_fu_1087_p2;
wire   [11:0] sub_ln570_fu_1093_p2;
wire  signed [11:0] sh_amt_fu_1099_p3;
wire   [53:0] man_V_12_fu_1068_p3;
wire  signed [31:0] sext_ln570_fu_1107_p1;
wire   [53:0] zext_ln575_fu_1127_p1;
wire   [53:0] ashr_ln575_fu_1131_p2;
wire   [31:0] bitcast_ln724_fu_1141_p1;
wire   [0:0] tmp_31_fu_1144_p3;
wire   [0:0] icmp_ln574_fu_1121_p2;
wire   [23:0] trunc_ln575_fu_1137_p1;
wire   [23:0] select_ln577_fu_1152_p3;
wire   [23:0] trunc_ln572_fu_1117_p1;
wire   [23:0] sext_ln570cast_fu_1174_p1;
wire   [0:0] icmp_ln592_fu_1168_p2;
wire   [23:0] shl_ln593_fu_1178_p2;
wire   [0:0] icmp_ln571_fu_1111_p2;
wire   [0:0] xor_ln560_fu_1192_p2;
wire   [0:0] and_ln571_fu_1197_p2;
wire   [23:0] select_ln592_fu_1184_p3;
wire   [0:0] or_ln571_fu_1211_p2;
wire   [0:0] xor_ln571_fu_1216_p2;
wire   [0:0] and_ln570_fu_1222_p2;
wire   [23:0] select_ln574_fu_1160_p3;
wire   [23:0] select_ln571_fu_1203_p3;
wire   [23:0] select_ln570_fu_1228_p3;
wire   [52:0] p_Result_62_fu_1252_p3;
wire   [53:0] zext_ln558_3_fu_1259_p1;
wire   [53:0] man_V_14_fu_1263_p2;
wire   [11:0] zext_ln455_3_fu_1249_p1;
wire   [11:0] F2_3_fu_1276_p2;
wire   [0:0] icmp_ln570_3_fu_1282_p2;
wire   [11:0] add_ln570_3_fu_1288_p2;
wire   [11:0] sub_ln570_3_fu_1294_p2;
wire  signed [11:0] sh_amt_3_fu_1300_p3;
wire   [53:0] man_V_15_fu_1269_p3;
wire  signed [31:0] sext_ln570_2_fu_1308_p1;
wire   [53:0] zext_ln575_3_fu_1328_p1;
wire   [53:0] ashr_ln575_3_fu_1332_p2;
wire   [31:0] bitcast_ln724_2_fu_1342_p1;
wire   [0:0] tmp_33_fu_1345_p3;
wire   [0:0] icmp_ln574_3_fu_1322_p2;
wire   [23:0] trunc_ln575_3_fu_1338_p1;
wire   [23:0] select_ln577_3_fu_1353_p3;
wire   [23:0] trunc_ln572_3_fu_1318_p1;
wire   [23:0] sext_ln570_2cast_fu_1375_p1;
wire   [0:0] icmp_ln592_3_fu_1369_p2;
wire   [23:0] shl_ln593_3_fu_1379_p2;
wire   [0:0] icmp_ln571_3_fu_1312_p2;
wire   [0:0] xor_ln560_2_fu_1393_p2;
wire   [0:0] and_ln571_2_fu_1398_p2;
wire   [23:0] select_ln592_3_fu_1385_p3;
wire   [0:0] or_ln571_2_fu_1412_p2;
wire   [0:0] xor_ln571_2_fu_1417_p2;
wire   [0:0] and_ln570_2_fu_1423_p2;
wire   [23:0] select_ln574_3_fu_1361_p3;
wire   [23:0] select_ln571_2_fu_1404_p3;
wire   [23:0] select_ln570_7_fu_1429_p3;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_start_reg = 1'b0;
#0 grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_start_reg = 1'b0;
end

tri2d_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1 grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_start),
    .ap_done(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_done),
    .ap_idle(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_idle),
    .ap_ready(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_ready),
    .p_out(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out),
    .p_out_ap_vld(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out_ap_vld),
    .p_out1(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out1),
    .p_out1_ap_vld(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out1_ap_vld),
    .p_out2(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out2),
    .p_out2_ap_vld(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out2_ap_vld),
    .p_out3(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out3),
    .p_out3_ap_vld(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out3_ap_vld),
    .vertex_used_V_address0(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_used_V_address0),
    .vertex_used_V_ce0(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_used_V_ce0),
    .vertex_used_V_q0(vertex_used_V_q0),
    .vertex_x_V_address0(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_x_V_address0),
    .vertex_x_V_ce0(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_x_V_ce0),
    .vertex_x_V_q0(vertex_x_V_q0),
    .vertex_y_V_address0(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_y_V_address0),
    .vertex_y_V_ce0(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_y_V_ce0),
    .vertex_y_V_q0(vertex_y_V_q0)
);

tri2d_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2 grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_start),
    .ap_done(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_done),
    .ap_idle(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_idle),
    .ap_ready(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_ready),
    .enhanced_grid_flat_cells_triangle_count_address0(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_enhanced_grid_flat_cells_triangle_count_address0),
    .enhanced_grid_flat_cells_triangle_count_ce0(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_enhanced_grid_flat_cells_triangle_count_ce0),
    .enhanced_grid_flat_cells_triangle_count_we0(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_enhanced_grid_flat_cells_triangle_count_we0),
    .enhanced_grid_flat_cells_triangle_count_d0(grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_enhanced_grid_flat_cells_triangle_count_d0)
);

tri2d_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_172_p0),
    .din1(32'd1015021568),
    .ce(1'b1),
    .dout(grp_fu_172_p2)
);

tri2d_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_177_p0),
    .din1(32'd1015021568),
    .ce(1'b1),
    .dout(grp_fu_177_p2)
);

tri2d_mul_25s_26ns_51_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 51 ))
mul_25s_26ns_51_1_1_U37(
    .din0(ret_V_fu_208_p2),
    .din1(r_V_45_fu_218_p1),
    .dout(r_V_45_fu_218_p2)
);

tri2d_mul_25s_26ns_51_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 51 ))
mul_25s_26ns_51_1_1_U38(
    .din0(ret_V_60_fu_232_p2),
    .din1(r_V_47_fu_242_p1),
    .dout(r_V_47_fu_242_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_start_reg <= 1'b1;
        end else if ((grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_ready == 1'b1)) begin
            grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_start_reg <= 1'b1;
        end else if ((grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_ready == 1'b1)) begin
            grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1090_2_reg_1500 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        LD_4_reg_1521 <= LD_4_fu_932_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1090_reg_1479 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        LD_reg_1516 <= LD_fu_656_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        exp_tmp_3_reg_1585 <= {{ireg_3_fu_994_p1[62:52]}};
        exp_tmp_reg_1563 <= {{ireg_fu_958_p1[62:52]}};
        icmp_ln560_3_reg_1595 <= icmp_ln560_3_fu_1024_p2;
        icmp_ln560_reg_1573 <= icmp_ln560_fu_988_p2;
        p_Result_59_reg_1558 <= ireg_fu_958_p1[32'd63];
        p_Result_61_reg_1580 <= ireg_3_fu_994_p1[32'd63];
        trunc_ln554_3_reg_1590 <= trunc_ln554_3_fu_1020_p1;
        trunc_ln554_reg_1568 <= trunc_ln554_fu_984_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln1090_2_reg_1500 <= icmp_ln1090_2_fu_364_p2;
        icmp_ln1090_reg_1479 <= icmp_ln1090_fu_330_p2;
        p_Result_53_reg_1484 <= ret_V_61_fu_324_p2[32'd24];
        p_Result_56_reg_1505 <= ret_V_62_fu_358_p2[32'd24];
        ret_V_61_reg_1474 <= ret_V_61_fu_324_p2;
        ret_V_62_reg_1495 <= ret_V_62_fu_358_p2;
        tmp_V_7_reg_1511 <= tmp_V_7_fu_378_p2;
        tmp_V_reg_1490 <= tmp_V_fu_344_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1090_2_reg_1500 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        phitmp1_reg_1541 <= grp_fu_177_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1090_reg_1479 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        phitmp_reg_1536 <= grp_fu_172_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        select_ln1090_1_reg_1552 <= select_ln1090_1_fu_951_p3;
        select_ln1090_reg_1546 <= select_ln1090_fu_944_p3;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        enhanced_grid_cell_height_V_ap_vld = 1'b1;
    end else begin
        enhanced_grid_cell_height_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        enhanced_grid_cell_width_V_ap_vld = 1'b1;
    end else begin
        enhanced_grid_cell_width_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        enhanced_grid_grid_size_x_ap_vld = 1'b1;
    end else begin
        enhanced_grid_grid_size_x_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        enhanced_grid_grid_size_y_ap_vld = 1'b1;
    end else begin
        enhanced_grid_grid_size_y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        enhanced_grid_total_cells_ap_vld = 1'b1;
    end else begin
        enhanced_grid_total_cells_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        enhanced_grid_x_max_V_ap_vld = 1'b1;
    end else begin
        enhanced_grid_x_max_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        enhanced_grid_x_min_V_ap_vld = 1'b1;
    end else begin
        enhanced_grid_x_min_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        enhanced_grid_y_max_V_ap_vld = 1'b1;
    end else begin
        enhanced_grid_y_max_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        enhanced_grid_y_min_V_ap_vld = 1'b1;
    end else begin
        enhanced_grid_y_min_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_3_fu_1276_p2 = (12'd1075 - zext_ln455_3_fu_1249_p1);

assign F2_fu_1075_p2 = (12'd1075 - zext_ln455_fu_1048_p1);

assign LD_4_fu_932_p1 = p_Result_58_fu_920_p5[31:0];

assign LD_fu_656_p1 = p_Result_55_fu_644_p5[31:0];

assign a_2_fu_759_p2 = (icmp_ln1102_2_fu_753_p2 & icmp_ln1101_2_fu_721_p2);

assign a_fu_483_p2 = (icmp_ln1102_fu_477_p2 & icmp_ln1101_fu_445_p2);

assign add_ln1104_1_fu_779_p2 = ($signed(trunc_ln1099_1_fu_701_p1) + $signed(25'd33554408));

assign add_ln1104_fu_503_p2 = ($signed(trunc_ln1099_fu_425_p1) + $signed(25'd33554408));

assign add_ln1113_1_fu_823_p2 = ($signed(sub_ln1099_2_fu_695_p2) + $signed(32'd4294967271));

assign add_ln1113_fu_547_p2 = ($signed(sub_ln1099_fu_419_p2) + $signed(32'd4294967271));

assign add_ln1124_2_fu_907_p2 = (sub_ln1119_2_fu_901_p2 + select_ln1098_2_fu_889_p3);

assign add_ln1124_fu_631_p2 = (sub_ln1119_fu_625_p2 + select_ln1098_fu_613_p3);

assign add_ln570_3_fu_1288_p2 = ($signed(F2_3_fu_1276_p2) + $signed(12'd4076));

assign add_ln570_fu_1087_p2 = ($signed(F2_fu_1075_p2) + $signed(12'd4076));

assign and_ln1104_2_fu_793_p2 = (xor_ln1104_2_fu_773_p2 & p_Result_46_fu_785_p3);

assign and_ln1104_fu_517_p2 = (xor_ln1104_fu_497_p2 & p_Result_39_fu_509_p3);

assign and_ln570_2_fu_1423_p2 = (xor_ln571_2_fu_1417_p2 & icmp_ln570_3_fu_1282_p2);

assign and_ln570_fu_1222_p2 = (xor_ln571_fu_1216_p2 & icmp_ln570_fu_1081_p2);

assign and_ln571_2_fu_1398_p2 = (xor_ln560_2_fu_1393_p2 & icmp_ln571_3_fu_1312_p2);

assign and_ln571_fu_1197_p2 = (xor_ln560_fu_1192_p2 & icmp_ln571_fu_1111_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_done == 1'b0) | (grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_done == 1'b0));
end

assign ashr_ln575_3_fu_1332_p2 = $signed(man_V_15_fu_1269_p3) >>> zext_ln575_3_fu_1328_p1;

assign ashr_ln575_fu_1131_p2 = $signed(man_V_12_fu_1068_p3) >>> zext_ln575_fu_1127_p1;

assign bitcast_ln724_2_fu_1342_p1 = select_ln1090_1_reg_1552;

assign bitcast_ln724_fu_1141_p1 = select_ln1090_reg_1546;

assign enhanced_grid_cell_height_V = ((icmp_ln560_3_reg_1595[0:0] == 1'b1) ? 24'd0 : select_ln570_7_fu_1429_p3);

assign enhanced_grid_cell_width_V = ((icmp_ln560_reg_1573[0:0] == 1'b1) ? 24'd0 : select_ln570_fu_1228_p3);

assign enhanced_grid_flat_cells_triangle_count_address0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_enhanced_grid_flat_cells_triangle_count_address0;

assign enhanced_grid_flat_cells_triangle_count_ce0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_enhanced_grid_flat_cells_triangle_count_ce0;

assign enhanced_grid_flat_cells_triangle_count_d0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_enhanced_grid_flat_cells_triangle_count_d0;

assign enhanced_grid_flat_cells_triangle_count_we0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_enhanced_grid_flat_cells_triangle_count_we0;

assign enhanced_grid_grid_size_x = 7'd64;

assign enhanced_grid_grid_size_y = 7'd64;

assign enhanced_grid_total_cells = 13'd4096;

assign enhanced_grid_x_max_V = lhs_V_fu_292_p2;

assign enhanced_grid_x_min_V = rhs_fu_258_p2;

assign enhanced_grid_y_max_V = lhs_V_3_fu_304_p2;

assign enhanced_grid_y_min_V = rhs_3_fu_280_p2;

assign grp_fu_1099_p_ce = 1'b1;

assign grp_fu_1099_p_din0 = select_ln1090_fu_944_p3;

assign grp_fu_1102_p_ce = 1'b1;

assign grp_fu_1102_p_din0 = select_ln1090_1_fu_951_p3;

assign grp_fu_172_p0 = LD_reg_1516;

assign grp_fu_177_p0 = LD_4_reg_1521;

assign grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_start = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_ap_start_reg;

assign grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_start = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_194_2_fu_166_ap_start_reg;

assign icmp_ln1090_2_fu_364_p2 = ((lhs_V_3_fu_304_p2 == rhs_3_fu_280_p2) ? 1'b1 : 1'b0);

assign icmp_ln1090_fu_330_p2 = ((lhs_V_fu_292_p2 == rhs_fu_258_p2) ? 1'b1 : 1'b0);

assign icmp_ln1101_2_fu_721_p2 = (($signed(tmp_27_fu_711_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1101_fu_445_p2 = (($signed(tmp_fu_435_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1102_2_fu_753_p2 = ((p_Result_45_fu_747_p2 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln1102_fu_477_p2 = ((p_Result_38_fu_471_p2 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln1113_1_fu_817_p2 = (($signed(lsb_index_2_fu_705_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1113_fu_541_p2 = (($signed(lsb_index_fu_429_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln560_3_fu_1024_p2 = ((trunc_ln544_3_fu_998_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln560_fu_988_p2 = ((trunc_ln544_fu_962_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln570_3_fu_1282_p2 = (($signed(F2_3_fu_1276_p2) > $signed(12'd20)) ? 1'b1 : 1'b0);

assign icmp_ln570_fu_1081_p2 = (($signed(F2_fu_1075_p2) > $signed(12'd20)) ? 1'b1 : 1'b0);

assign icmp_ln571_3_fu_1312_p2 = ((F2_3_fu_1276_p2 == 12'd20) ? 1'b1 : 1'b0);

assign icmp_ln571_fu_1111_p2 = ((F2_fu_1075_p2 == 12'd20) ? 1'b1 : 1'b0);

assign icmp_ln574_3_fu_1322_p2 = ((sh_amt_3_fu_1300_p3 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln574_fu_1121_p2 = ((sh_amt_fu_1099_p3 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln592_3_fu_1369_p2 = ((sh_amt_3_fu_1300_p3 < 12'd24) ? 1'b1 : 1'b0);

assign icmp_ln592_fu_1168_p2 = ((sh_amt_fu_1099_p3 < 12'd24) ? 1'b1 : 1'b0);

assign ireg_3_fu_994_p1 = grp_fu_1102_p_dout0;

assign ireg_fu_958_p1 = grp_fu_1099_p_dout0;


always @ (sext_ln1198_1_fu_683_p1) begin
    if (sext_ln1198_1_fu_683_p1[0] == 1'b1) begin
        l_2_fu_687_p3 = 32'd0;
    end else if (sext_ln1198_1_fu_683_p1[1] == 1'b1) begin
        l_2_fu_687_p3 = 32'd1;
    end else if (sext_ln1198_1_fu_683_p1[2] == 1'b1) begin
        l_2_fu_687_p3 = 32'd2;
    end else if (sext_ln1198_1_fu_683_p1[3] == 1'b1) begin
        l_2_fu_687_p3 = 32'd3;
    end else if (sext_ln1198_1_fu_683_p1[4] == 1'b1) begin
        l_2_fu_687_p3 = 32'd4;
    end else if (sext_ln1198_1_fu_683_p1[5] == 1'b1) begin
        l_2_fu_687_p3 = 32'd5;
    end else if (sext_ln1198_1_fu_683_p1[6] == 1'b1) begin
        l_2_fu_687_p3 = 32'd6;
    end else if (sext_ln1198_1_fu_683_p1[7] == 1'b1) begin
        l_2_fu_687_p3 = 32'd7;
    end else if (sext_ln1198_1_fu_683_p1[8] == 1'b1) begin
        l_2_fu_687_p3 = 32'd8;
    end else if (sext_ln1198_1_fu_683_p1[9] == 1'b1) begin
        l_2_fu_687_p3 = 32'd9;
    end else if (sext_ln1198_1_fu_683_p1[10] == 1'b1) begin
        l_2_fu_687_p3 = 32'd10;
    end else if (sext_ln1198_1_fu_683_p1[11] == 1'b1) begin
        l_2_fu_687_p3 = 32'd11;
    end else if (sext_ln1198_1_fu_683_p1[12] == 1'b1) begin
        l_2_fu_687_p3 = 32'd12;
    end else if (sext_ln1198_1_fu_683_p1[13] == 1'b1) begin
        l_2_fu_687_p3 = 32'd13;
    end else if (sext_ln1198_1_fu_683_p1[14] == 1'b1) begin
        l_2_fu_687_p3 = 32'd14;
    end else if (sext_ln1198_1_fu_683_p1[15] == 1'b1) begin
        l_2_fu_687_p3 = 32'd15;
    end else if (sext_ln1198_1_fu_683_p1[16] == 1'b1) begin
        l_2_fu_687_p3 = 32'd16;
    end else if (sext_ln1198_1_fu_683_p1[17] == 1'b1) begin
        l_2_fu_687_p3 = 32'd17;
    end else if (sext_ln1198_1_fu_683_p1[18] == 1'b1) begin
        l_2_fu_687_p3 = 32'd18;
    end else if (sext_ln1198_1_fu_683_p1[19] == 1'b1) begin
        l_2_fu_687_p3 = 32'd19;
    end else if (sext_ln1198_1_fu_683_p1[20] == 1'b1) begin
        l_2_fu_687_p3 = 32'd20;
    end else if (sext_ln1198_1_fu_683_p1[21] == 1'b1) begin
        l_2_fu_687_p3 = 32'd21;
    end else if (sext_ln1198_1_fu_683_p1[22] == 1'b1) begin
        l_2_fu_687_p3 = 32'd22;
    end else if (sext_ln1198_1_fu_683_p1[23] == 1'b1) begin
        l_2_fu_687_p3 = 32'd23;
    end else if (sext_ln1198_1_fu_683_p1[24] == 1'b1) begin
        l_2_fu_687_p3 = 32'd24;
    end else if (sext_ln1198_1_fu_683_p1[25] == 1'b1) begin
        l_2_fu_687_p3 = 32'd25;
    end else if (sext_ln1198_1_fu_683_p1[26] == 1'b1) begin
        l_2_fu_687_p3 = 32'd26;
    end else if (sext_ln1198_1_fu_683_p1[27] == 1'b1) begin
        l_2_fu_687_p3 = 32'd27;
    end else if (sext_ln1198_1_fu_683_p1[28] == 1'b1) begin
        l_2_fu_687_p3 = 32'd28;
    end else if (sext_ln1198_1_fu_683_p1[29] == 1'b1) begin
        l_2_fu_687_p3 = 32'd29;
    end else if (sext_ln1198_1_fu_683_p1[30] == 1'b1) begin
        l_2_fu_687_p3 = 32'd30;
    end else if (sext_ln1198_1_fu_683_p1[31] == 1'b1) begin
        l_2_fu_687_p3 = 32'd31;
    end else begin
        l_2_fu_687_p3 = 32'd32;
    end
end


always @ (sext_ln1198_fu_407_p1) begin
    if (sext_ln1198_fu_407_p1[0] == 1'b1) begin
        l_fu_411_p3 = 32'd0;
    end else if (sext_ln1198_fu_407_p1[1] == 1'b1) begin
        l_fu_411_p3 = 32'd1;
    end else if (sext_ln1198_fu_407_p1[2] == 1'b1) begin
        l_fu_411_p3 = 32'd2;
    end else if (sext_ln1198_fu_407_p1[3] == 1'b1) begin
        l_fu_411_p3 = 32'd3;
    end else if (sext_ln1198_fu_407_p1[4] == 1'b1) begin
        l_fu_411_p3 = 32'd4;
    end else if (sext_ln1198_fu_407_p1[5] == 1'b1) begin
        l_fu_411_p3 = 32'd5;
    end else if (sext_ln1198_fu_407_p1[6] == 1'b1) begin
        l_fu_411_p3 = 32'd6;
    end else if (sext_ln1198_fu_407_p1[7] == 1'b1) begin
        l_fu_411_p3 = 32'd7;
    end else if (sext_ln1198_fu_407_p1[8] == 1'b1) begin
        l_fu_411_p3 = 32'd8;
    end else if (sext_ln1198_fu_407_p1[9] == 1'b1) begin
        l_fu_411_p3 = 32'd9;
    end else if (sext_ln1198_fu_407_p1[10] == 1'b1) begin
        l_fu_411_p3 = 32'd10;
    end else if (sext_ln1198_fu_407_p1[11] == 1'b1) begin
        l_fu_411_p3 = 32'd11;
    end else if (sext_ln1198_fu_407_p1[12] == 1'b1) begin
        l_fu_411_p3 = 32'd12;
    end else if (sext_ln1198_fu_407_p1[13] == 1'b1) begin
        l_fu_411_p3 = 32'd13;
    end else if (sext_ln1198_fu_407_p1[14] == 1'b1) begin
        l_fu_411_p3 = 32'd14;
    end else if (sext_ln1198_fu_407_p1[15] == 1'b1) begin
        l_fu_411_p3 = 32'd15;
    end else if (sext_ln1198_fu_407_p1[16] == 1'b1) begin
        l_fu_411_p3 = 32'd16;
    end else if (sext_ln1198_fu_407_p1[17] == 1'b1) begin
        l_fu_411_p3 = 32'd17;
    end else if (sext_ln1198_fu_407_p1[18] == 1'b1) begin
        l_fu_411_p3 = 32'd18;
    end else if (sext_ln1198_fu_407_p1[19] == 1'b1) begin
        l_fu_411_p3 = 32'd19;
    end else if (sext_ln1198_fu_407_p1[20] == 1'b1) begin
        l_fu_411_p3 = 32'd20;
    end else if (sext_ln1198_fu_407_p1[21] == 1'b1) begin
        l_fu_411_p3 = 32'd21;
    end else if (sext_ln1198_fu_407_p1[22] == 1'b1) begin
        l_fu_411_p3 = 32'd22;
    end else if (sext_ln1198_fu_407_p1[23] == 1'b1) begin
        l_fu_411_p3 = 32'd23;
    end else if (sext_ln1198_fu_407_p1[24] == 1'b1) begin
        l_fu_411_p3 = 32'd24;
    end else if (sext_ln1198_fu_407_p1[25] == 1'b1) begin
        l_fu_411_p3 = 32'd25;
    end else if (sext_ln1198_fu_407_p1[26] == 1'b1) begin
        l_fu_411_p3 = 32'd26;
    end else if (sext_ln1198_fu_407_p1[27] == 1'b1) begin
        l_fu_411_p3 = 32'd27;
    end else if (sext_ln1198_fu_407_p1[28] == 1'b1) begin
        l_fu_411_p3 = 32'd28;
    end else if (sext_ln1198_fu_407_p1[29] == 1'b1) begin
        l_fu_411_p3 = 32'd29;
    end else if (sext_ln1198_fu_407_p1[30] == 1'b1) begin
        l_fu_411_p3 = 32'd30;
    end else if (sext_ln1198_fu_407_p1[31] == 1'b1) begin
        l_fu_411_p3 = 32'd31;
    end else begin
        l_fu_411_p3 = 32'd32;
    end
end

assign lhs_V_3_fu_304_p1 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out1;

assign lhs_V_3_fu_304_p2 = ($signed(trunc_ln818_1_fu_270_p4) + $signed(lhs_V_3_fu_304_p1));

assign lhs_V_fu_292_p1 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out3;

assign lhs_V_fu_292_p2 = ($signed(trunc_ln_fu_248_p4) + $signed(lhs_V_fu_292_p1));

assign lsb_index_2_fu_705_p2 = ($signed(sub_ln1099_2_fu_695_p2) + $signed(32'd4294967272));

assign lsb_index_fu_429_p2 = ($signed(sub_ln1099_fu_419_p2) + $signed(32'd4294967272));

assign lshr_ln1102_2_fu_741_p2 = 25'd33554431 >> zext_ln1102_2_fu_737_p1;

assign lshr_ln1102_fu_465_p2 = 25'd33554431 >> zext_ln1102_fu_461_p1;

assign lshr_ln1113_1_fu_833_p2 = zext_ln1112_1_fu_813_p1 >> zext_ln1113_1_fu_829_p1;

assign lshr_ln1113_fu_557_p2 = zext_ln1112_fu_537_p1 >> zext_ln1113_fu_553_p1;

assign m_10_fu_849_p3 = ((icmp_ln1113_1_fu_817_p2[0:0] == 1'b1) ? lshr_ln1113_1_fu_833_p2 : shl_ln1114_1_fu_843_p2);

assign m_11_fu_861_p2 = (m_10_fu_849_p3 + zext_ln1116_2_fu_857_p1);

assign m_14_fu_591_p4 = {{m_8_fu_585_p2[63:1]}};

assign m_7_fu_573_p3 = ((icmp_ln1113_fu_541_p2[0:0] == 1'b1) ? lshr_ln1113_fu_557_p2 : shl_ln1114_fu_567_p2);

assign m_8_fu_585_p2 = (m_7_fu_573_p3 + zext_ln1116_fu_581_p1);

assign m_fu_867_p4 = {{m_11_fu_861_p2[63:1]}};

assign man_V_11_fu_1062_p2 = (54'd0 - zext_ln558_fu_1058_p1);

assign man_V_12_fu_1068_p3 = ((p_Result_59_reg_1558[0:0] == 1'b1) ? man_V_11_fu_1062_p2 : zext_ln558_fu_1058_p1);

assign man_V_14_fu_1263_p2 = (54'd0 - zext_ln558_3_fu_1259_p1);

assign man_V_15_fu_1269_p3 = ((p_Result_61_reg_1580[0:0] == 1'b1) ? man_V_14_fu_1263_p2 : zext_ln558_3_fu_1259_p1);

assign or_ln1104_2_fu_805_p3 = {{1'd0}, {or_ln1104_fu_799_p2}};

assign or_ln1104_3_fu_523_p2 = (and_ln1104_fu_517_p2 | a_fu_483_p2);

assign or_ln1104_fu_799_p2 = (and_ln1104_2_fu_793_p2 | a_2_fu_759_p2);

assign or_ln571_2_fu_1412_p2 = (icmp_ln571_3_fu_1312_p2 | icmp_ln560_3_reg_1595);

assign or_ln571_fu_1211_p2 = (icmp_ln571_fu_1111_p2 | icmp_ln560_reg_1573);

assign or_ln_fu_529_p3 = {{1'd0}, {or_ln1104_3_fu_523_p2}};

assign p_Result_38_fu_471_p2 = (tmp_V_9_fu_384_p3 & lshr_ln1102_fu_465_p2);

assign p_Result_39_fu_509_p3 = tmp_V_9_fu_384_p3[add_ln1104_fu_503_p2];

assign p_Result_40_fu_605_p3 = m_8_fu_585_p2[32'd25];

integer ap_tvar_int_0;

always @ (tmp_V_10_fu_660_p3) begin
    for (ap_tvar_int_0 = 25 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 24 - 0) begin
            p_Result_43_fu_665_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_43_fu_665_p4[ap_tvar_int_0] = tmp_V_10_fu_660_p3[24 - ap_tvar_int_0];
        end
    end
end

assign p_Result_45_fu_747_p2 = (tmp_V_10_fu_660_p3 & lshr_ln1102_2_fu_741_p2);

assign p_Result_46_fu_785_p3 = tmp_V_10_fu_660_p3[add_ln1104_1_fu_779_p2];

assign p_Result_47_fu_881_p3 = m_11_fu_861_p2[32'd25];

assign p_Result_54_fu_399_p3 = {{1'd1}, {p_Result_s_fu_389_p4}};

assign p_Result_55_fu_644_p5 = {{zext_ln1117_fu_601_p1[63:32]}, {tmp_3_fu_637_p3}, {zext_ln1117_fu_601_p1[22:0]}};

assign p_Result_57_fu_675_p3 = {{1'd1}, {p_Result_43_fu_665_p4}};

assign p_Result_58_fu_920_p5 = {{zext_ln1117_1_fu_877_p1[63:32]}, {tmp_4_fu_913_p3}, {zext_ln1117_1_fu_877_p1[22:0]}};

assign p_Result_60_fu_1051_p3 = {{1'd1}, {trunc_ln554_reg_1568}};

assign p_Result_62_fu_1252_p3 = {{1'd1}, {trunc_ln554_3_reg_1590}};

integer ap_tvar_int_1;

always @ (tmp_V_9_fu_384_p3) begin
    for (ap_tvar_int_1 = 25 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 24 - 0) begin
            p_Result_s_fu_389_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_s_fu_389_p4[ap_tvar_int_1] = tmp_V_9_fu_384_p3[24 - ap_tvar_int_1];
        end
    end
end

assign r_V_45_fu_218_p1 = 51'd26843545;

assign r_V_47_fu_242_p1 = 51'd26843545;

assign ret_V_60_fu_232_p2 = ($signed(sext_ln1348_22_fu_224_p1) - $signed(sext_ln1348_23_fu_228_p1));

assign ret_V_61_fu_324_p2 = ($signed(sext_ln813_fu_316_p1) - $signed(sext_ln813_7_fu_320_p1));

assign ret_V_62_fu_358_p2 = ($signed(sext_ln813_8_fu_350_p1) - $signed(sext_ln813_9_fu_354_p1));

assign ret_V_fu_208_p2 = ($signed(sext_ln1348_fu_200_p1) - $signed(sext_ln1348_21_fu_204_p1));

assign rhs_3_fu_280_p0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out;

assign rhs_3_fu_280_p2 = ($signed(rhs_3_fu_280_p0) - $signed(trunc_ln818_1_fu_270_p4));

assign rhs_fu_258_p0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out2;

assign rhs_fu_258_p2 = ($signed(rhs_fu_258_p0) - $signed(trunc_ln_fu_248_p4));

assign select_ln1090_1_fu_951_p3 = ((icmp_ln1090_2_reg_1500[0:0] == 1'b1) ? 32'd0 : phitmp1_reg_1541);

assign select_ln1090_fu_944_p3 = ((icmp_ln1090_reg_1479[0:0] == 1'b1) ? 32'd0 : phitmp_reg_1536);

assign select_ln1098_2_fu_889_p3 = ((p_Result_47_fu_881_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln1098_fu_613_p3 = ((p_Result_40_fu_605_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln570_7_fu_1429_p3 = ((and_ln570_2_fu_1423_p2[0:0] == 1'b1) ? select_ln574_3_fu_1361_p3 : select_ln571_2_fu_1404_p3);

assign select_ln570_fu_1228_p3 = ((and_ln570_fu_1222_p2[0:0] == 1'b1) ? select_ln574_fu_1160_p3 : select_ln571_fu_1203_p3);

assign select_ln571_2_fu_1404_p3 = ((and_ln571_2_fu_1398_p2[0:0] == 1'b1) ? trunc_ln572_3_fu_1318_p1 : select_ln592_3_fu_1385_p3);

assign select_ln571_fu_1203_p3 = ((and_ln571_fu_1197_p2[0:0] == 1'b1) ? trunc_ln572_fu_1117_p1 : select_ln592_fu_1184_p3);

assign select_ln574_3_fu_1361_p3 = ((icmp_ln574_3_fu_1322_p2[0:0] == 1'b1) ? trunc_ln575_3_fu_1338_p1 : select_ln577_3_fu_1353_p3);

assign select_ln574_fu_1160_p3 = ((icmp_ln574_fu_1121_p2[0:0] == 1'b1) ? trunc_ln575_fu_1137_p1 : select_ln577_fu_1152_p3);

assign select_ln577_3_fu_1353_p3 = ((tmp_33_fu_1345_p3[0:0] == 1'b1) ? 24'd16777215 : 24'd0);

assign select_ln577_fu_1152_p3 = ((tmp_31_fu_1144_p3[0:0] == 1'b1) ? 24'd16777215 : 24'd0);

assign select_ln592_3_fu_1385_p3 = ((icmp_ln592_3_fu_1369_p2[0:0] == 1'b1) ? shl_ln593_3_fu_1379_p2 : 24'd0);

assign select_ln592_fu_1184_p3 = ((icmp_ln592_fu_1168_p2[0:0] == 1'b1) ? shl_ln593_fu_1178_p2 : 24'd0);

assign sext_ln1198_1_fu_683_p1 = $signed(p_Result_57_fu_675_p3);

assign sext_ln1198_fu_407_p1 = $signed(p_Result_54_fu_399_p3);

assign sext_ln1348_21_fu_204_p0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out2;

assign sext_ln1348_21_fu_204_p1 = sext_ln1348_21_fu_204_p0;

assign sext_ln1348_22_fu_224_p0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out1;

assign sext_ln1348_22_fu_224_p1 = sext_ln1348_22_fu_224_p0;

assign sext_ln1348_23_fu_228_p0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out;

assign sext_ln1348_23_fu_228_p1 = sext_ln1348_23_fu_228_p0;

assign sext_ln1348_fu_200_p0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_p_out3;

assign sext_ln1348_fu_200_p1 = sext_ln1348_fu_200_p0;

assign sext_ln570_2_fu_1308_p1 = sh_amt_3_fu_1300_p3;

assign sext_ln570_2cast_fu_1375_p1 = sext_ln570_2_fu_1308_p1[23:0];

assign sext_ln570_fu_1107_p1 = sh_amt_fu_1099_p3;

assign sext_ln570cast_fu_1174_p1 = sext_ln570_fu_1107_p1[23:0];

assign sext_ln813_7_fu_320_p1 = rhs_fu_258_p2;

assign sext_ln813_8_fu_350_p1 = lhs_V_3_fu_304_p2;

assign sext_ln813_9_fu_354_p1 = rhs_3_fu_280_p2;

assign sext_ln813_fu_316_p1 = lhs_V_fu_292_p2;

assign sh_amt_3_fu_1300_p3 = ((icmp_ln570_3_fu_1282_p2[0:0] == 1'b1) ? add_ln570_3_fu_1288_p2 : sub_ln570_3_fu_1294_p2);

assign sh_amt_fu_1099_p3 = ((icmp_ln570_fu_1081_p2[0:0] == 1'b1) ? add_ln570_fu_1087_p2 : sub_ln570_fu_1093_p2);

assign shl_ln1114_1_fu_843_p2 = zext_ln1112_1_fu_813_p1 << zext_ln1114_1_fu_839_p1;

assign shl_ln1114_fu_567_p2 = zext_ln1112_fu_537_p1 << zext_ln1114_fu_563_p1;

assign shl_ln593_3_fu_1379_p2 = trunc_ln572_3_fu_1318_p1 << sext_ln570_2cast_fu_1375_p1;

assign shl_ln593_fu_1178_p2 = trunc_ln572_fu_1117_p1 << sext_ln570cast_fu_1174_p1;

assign sub_ln1099_2_fu_695_p2 = (32'd25 - l_2_fu_687_p3);

assign sub_ln1099_fu_419_p2 = (32'd25 - l_fu_411_p3);

assign sub_ln1102_2_fu_731_p2 = ($signed(5'd18) - $signed(trunc_ln1102_2_fu_727_p1));

assign sub_ln1102_fu_455_p2 = ($signed(5'd18) - $signed(trunc_ln1102_fu_451_p1));

assign sub_ln1119_2_fu_901_p2 = (8'd5 - trunc_ln1098_2_fu_897_p1);

assign sub_ln1119_fu_625_p2 = (8'd5 - trunc_ln1098_fu_621_p1);

assign sub_ln570_3_fu_1294_p2 = (12'd20 - F2_3_fu_1276_p2);

assign sub_ln570_fu_1093_p2 = (12'd20 - F2_fu_1075_p2);

assign tmp_24_fu_489_p3 = lsb_index_fu_429_p2[32'd31];

assign tmp_27_fu_711_p4 = {{lsb_index_2_fu_705_p2[31:1]}};

assign tmp_28_fu_765_p3 = lsb_index_2_fu_705_p2[32'd31];

assign tmp_31_fu_1144_p3 = bitcast_ln724_fu_1141_p1[32'd31];

assign tmp_33_fu_1345_p3 = bitcast_ln724_2_fu_1342_p1[32'd31];

assign tmp_3_fu_637_p3 = {{p_Result_53_reg_1484}, {add_ln1124_fu_631_p2}};

assign tmp_4_fu_913_p3 = {{p_Result_56_reg_1505}, {add_ln1124_2_fu_907_p2}};

assign tmp_V_10_fu_660_p3 = ((p_Result_56_reg_1505[0:0] == 1'b1) ? tmp_V_7_reg_1511 : ret_V_62_reg_1495);

assign tmp_V_7_fu_378_p2 = (25'd0 - ret_V_62_fu_358_p2);

assign tmp_V_9_fu_384_p3 = ((p_Result_53_reg_1484[0:0] == 1'b1) ? tmp_V_reg_1490 : ret_V_61_reg_1474);

assign tmp_V_fu_344_p2 = (25'd0 - ret_V_61_fu_324_p2);

assign tmp_fu_435_p4 = {{lsb_index_fu_429_p2[31:1]}};

assign trunc_ln1098_2_fu_897_p1 = l_2_fu_687_p3[7:0];

assign trunc_ln1098_fu_621_p1 = l_fu_411_p3[7:0];

assign trunc_ln1099_1_fu_701_p1 = sub_ln1099_2_fu_695_p2[24:0];

assign trunc_ln1099_fu_425_p1 = sub_ln1099_fu_419_p2[24:0];

assign trunc_ln1102_2_fu_727_p1 = sub_ln1099_2_fu_695_p2[4:0];

assign trunc_ln1102_fu_451_p1 = sub_ln1099_fu_419_p2[4:0];

assign trunc_ln544_3_fu_998_p1 = ireg_3_fu_994_p1[62:0];

assign trunc_ln544_fu_962_p1 = ireg_fu_958_p1[62:0];

assign trunc_ln554_3_fu_1020_p1 = ireg_3_fu_994_p1[51:0];

assign trunc_ln554_fu_984_p1 = ireg_fu_958_p1[51:0];

assign trunc_ln572_3_fu_1318_p1 = man_V_15_fu_1269_p3[23:0];

assign trunc_ln572_fu_1117_p1 = man_V_12_fu_1068_p3[23:0];

assign trunc_ln575_3_fu_1338_p1 = ashr_ln575_3_fu_1332_p2[23:0];

assign trunc_ln575_fu_1137_p1 = ashr_ln575_fu_1131_p2[23:0];

assign trunc_ln818_1_fu_270_p4 = {{r_V_47_fu_242_p2[50:27]}};

assign trunc_ln_fu_248_p4 = {{r_V_45_fu_218_p2[50:27]}};

assign vertex_used_V_address0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_used_V_address0;

assign vertex_used_V_ce0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_used_V_ce0;

assign vertex_x_V_address0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_x_V_address0;

assign vertex_x_V_ce0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_x_V_ce0;

assign vertex_y_V_address0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_y_V_address0;

assign vertex_y_V_ce0 = grp_initEnhancedGrid_Pipeline_VITIS_LOOP_162_1_fu_152_vertex_y_V_ce0;

assign xor_ln1104_2_fu_773_p2 = (tmp_28_fu_765_p3 ^ 1'd1);

assign xor_ln1104_fu_497_p2 = (tmp_24_fu_489_p3 ^ 1'd1);

assign xor_ln560_2_fu_1393_p2 = (icmp_ln560_3_reg_1595 ^ 1'd1);

assign xor_ln560_fu_1192_p2 = (icmp_ln560_reg_1573 ^ 1'd1);

assign xor_ln571_2_fu_1417_p2 = (or_ln571_2_fu_1412_p2 ^ 1'd1);

assign xor_ln571_fu_1216_p2 = (or_ln571_fu_1211_p2 ^ 1'd1);

assign zext_ln1102_2_fu_737_p1 = sub_ln1102_2_fu_731_p2;

assign zext_ln1102_fu_461_p1 = sub_ln1102_fu_455_p2;

assign zext_ln1112_1_fu_813_p1 = tmp_V_10_fu_660_p3;

assign zext_ln1112_fu_537_p1 = tmp_V_9_fu_384_p3;

assign zext_ln1113_1_fu_829_p1 = add_ln1113_1_fu_823_p2;

assign zext_ln1113_fu_553_p1 = add_ln1113_fu_547_p2;

assign zext_ln1114_1_fu_839_p1 = l_2_fu_687_p3;

assign zext_ln1114_fu_563_p1 = l_fu_411_p3;

assign zext_ln1116_2_fu_857_p1 = or_ln1104_2_fu_805_p3;

assign zext_ln1116_fu_581_p1 = or_ln_fu_529_p3;

assign zext_ln1117_1_fu_877_p1 = m_fu_867_p4;

assign zext_ln1117_fu_601_p1 = m_14_fu_591_p4;

assign zext_ln455_3_fu_1249_p1 = exp_tmp_3_reg_1585;

assign zext_ln455_fu_1048_p1 = exp_tmp_reg_1563;

assign zext_ln558_3_fu_1259_p1 = p_Result_62_fu_1252_p3;

assign zext_ln558_fu_1058_p1 = p_Result_60_fu_1051_p3;

assign zext_ln575_3_fu_1328_p1 = $unsigned(sext_ln570_2_fu_1308_p1);

assign zext_ln575_fu_1127_p1 = $unsigned(sext_ln570_fu_1107_p1);

endmodule //tri2d_initEnhancedGrid
