// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tri2d_getHilbertCode (
        ap_clk,
        ap_rst,
        x,
        y,
        x_min,
        y_min,
        x_max,
        y_max,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [23:0] x;
input  [23:0] y;
input  [23:0] x_min;
input  [23:0] y_min;
input  [23:0] x_max;
input  [23:0] y_max;
output  [15:0] ap_return;

reg   [23:0] y_max_read_reg_3261;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_pp0_stage0_11001;
reg   [23:0] x_max_read_reg_3267;
reg   [23:0] y_min_read_reg_3273;
reg   [23:0] x_min_read_reg_3279;
reg   [23:0] y_read_reg_3285;
reg   [23:0] x_read_reg_3291;
reg   [0:0] p_Result_110_reg_3297;
wire   [23:0] tmp_V_fu_234_p2;
reg   [23:0] tmp_V_reg_3303;
reg   [0:0] p_Result_113_reg_3308;
wire   [23:0] tmp_V_12_fu_248_p2;
reg   [23:0] tmp_V_12_reg_3314;
reg   [0:0] p_Result_116_reg_3319;
wire   [23:0] tmp_V_14_fu_262_p2;
reg   [23:0] tmp_V_14_reg_3325;
reg   [0:0] p_Result_119_reg_3330;
wire   [23:0] tmp_V_16_fu_276_p2;
reg   [23:0] tmp_V_16_reg_3336;
reg   [0:0] p_Result_122_reg_3341;
wire   [23:0] tmp_V_18_fu_290_p2;
reg   [23:0] tmp_V_18_reg_3347;
reg   [0:0] p_Result_125_reg_3352;
wire   [23:0] tmp_V_20_fu_304_p2;
reg   [23:0] tmp_V_20_reg_3358;
wire   [31:0] x_f_fu_601_p3;
reg   [31:0] x_f_reg_3363;
wire   [31:0] y_f_fu_900_p3;
reg   [31:0] y_f_reg_3368;
wire   [31:0] xmin_f_fu_1199_p3;
reg   [31:0] xmin_f_reg_3373;
wire   [31:0] ymin_f_fu_1498_p3;
reg   [31:0] ymin_f_reg_3379;
wire   [31:0] xmax_f_fu_1797_p3;
reg   [31:0] xmax_f_reg_3385;
wire   [31:0] ymax_f_fu_2096_p3;
reg   [31:0] ymax_f_reg_3390;
wire   [31:0] grp_fu_172_p2;
reg   [31:0] sub_reg_3395;
wire   [31:0] grp_fu_176_p2;
reg   [31:0] sub6_reg_3400;
wire   [31:0] grp_fu_180_p2;
reg   [31:0] sub7_reg_3405;
wire   [31:0] grp_fu_184_p2;
reg   [31:0] sub8_reg_3410;
wire   [31:0] grp_fu_198_p2;
reg   [31:0] div_reg_3415;
reg   [31:0] div_reg_3415_pp0_iter15_reg;
wire   [31:0] grp_fu_202_p2;
reg   [31:0] div9_reg_3422;
reg   [31:0] div9_reg_3422_pp0_iter15_reg;
wire   [31:0] select_ln224_fu_2145_p3;
reg   [31:0] select_ln224_reg_3429;
wire   [31:0] select_ln224_2_fu_2193_p3;
reg   [31:0] select_ln224_2_reg_3436;
wire   [0:0] icmp_ln224_fu_2217_p2;
reg   [0:0] icmp_ln224_reg_3443;
reg   [0:0] icmp_ln224_reg_3443_pp0_iter18_reg;
reg   [0:0] icmp_ln224_reg_3443_pp0_iter19_reg;
wire   [0:0] icmp_ln224_2_fu_2223_p2;
reg   [0:0] icmp_ln224_2_reg_3448;
reg   [0:0] icmp_ln224_2_reg_3448_pp0_iter18_reg;
reg   [0:0] icmp_ln224_2_reg_3448_pp0_iter19_reg;
wire   [0:0] icmp_ln224_3_fu_2246_p2;
reg   [0:0] icmp_ln224_3_reg_3453;
reg   [0:0] icmp_ln224_3_reg_3453_pp0_iter18_reg;
reg   [0:0] icmp_ln224_3_reg_3453_pp0_iter19_reg;
wire   [0:0] icmp_ln224_4_fu_2252_p2;
reg   [0:0] icmp_ln224_4_reg_3458;
reg   [0:0] icmp_ln224_4_reg_3458_pp0_iter18_reg;
reg   [0:0] icmp_ln224_4_reg_3458_pp0_iter19_reg;
wire   [0:0] grp_fu_216_p2;
reg   [0:0] tmp_2_reg_3463;
reg   [0:0] tmp_2_reg_3463_pp0_iter19_reg;
wire   [0:0] grp_fu_221_p2;
reg   [0:0] tmp_12_reg_3468;
reg   [0:0] tmp_12_reg_3468_pp0_iter19_reg;
wire   [31:0] grp_fu_188_p2;
reg   [31:0] retval_0_i1248_op_reg_3473;
wire   [31:0] grp_fu_193_p2;
reg   [31:0] retval_0_i1650_op_reg_3478;
wire   [0:0] rx_fu_2423_p1;
reg   [0:0] rx_reg_3483;
wire   [0:0] ry_fu_2574_p1;
reg   [0:0] ry_reg_3488;
wire   [7:0] select_ln93_fu_2606_p3;
reg   [7:0] select_ln93_reg_3493;
wire   [7:0] select_ln93_1_fu_2614_p3;
reg   [7:0] select_ln93_1_reg_3500;
reg   [0:0] tmp_66_reg_3507;
reg   [0:0] tmp_67_reg_3513;
wire   [1:0] xor_ln95_1_fu_2666_p2;
reg   [1:0] xor_ln95_1_reg_3519;
wire    ap_block_pp0_stage0;
wire   [23:0] tmp_V_22_fu_315_p3;
reg   [23:0] p_Result_s_fu_320_p4;
wire   [24:0] p_Result_111_fu_330_p3;
wire  signed [31:0] sext_ln1198_fu_338_p1;
reg   [31:0] l_fu_342_p3;
wire   [31:0] sub_ln1099_fu_350_p2;
wire   [31:0] lsb_index_fu_360_p2;
wire   [30:0] tmp_35_fu_366_p4;
wire   [4:0] trunc_ln1102_fu_382_p1;
wire   [4:0] sub_ln1102_fu_386_p2;
wire   [23:0] zext_ln1102_fu_392_p1;
wire   [23:0] lshr_ln1102_fu_396_p2;
wire   [23:0] p_Result_65_fu_402_p2;
wire   [0:0] icmp_ln1101_fu_376_p2;
wire   [0:0] icmp_ln1102_fu_408_p2;
wire   [0:0] tmp_36_fu_420_p3;
wire   [23:0] trunc_ln1099_fu_356_p1;
wire   [23:0] add_ln1104_fu_434_p2;
wire   [0:0] p_Result_66_fu_440_p3;
wire   [0:0] xor_ln1104_fu_428_p2;
wire   [0:0] and_ln1104_fu_448_p2;
wire   [0:0] a_fu_414_p2;
wire   [0:0] or_ln1104_8_fu_454_p2;
wire   [31:0] add_ln1113_fu_478_p2;
wire   [63:0] zext_ln1112_fu_468_p1;
wire   [63:0] zext_ln1113_fu_484_p1;
wire   [31:0] sub_ln1114_fu_494_p2;
wire   [63:0] zext_ln1114_fu_500_p1;
wire   [0:0] icmp_ln1113_fu_472_p2;
wire   [63:0] lshr_ln1113_fu_488_p2;
wire   [63:0] shl_ln1114_fu_504_p2;
wire   [1:0] or_ln_fu_460_p3;
wire   [63:0] m_16_fu_510_p3;
wire   [63:0] zext_ln1116_fu_518_p1;
wire   [63:0] m_17_fu_522_p2;
wire   [62:0] m_39_fu_528_p4;
wire   [0:0] p_Result_67_fu_542_p3;
wire   [7:0] trunc_ln1098_fu_558_p1;
wire   [7:0] sub_ln1119_fu_562_p2;
wire   [7:0] select_ln1098_fu_550_p3;
wire   [7:0] add_ln1124_fu_568_p2;
wire   [63:0] zext_ln1117_fu_538_p1;
wire   [8:0] tmp_s_fu_574_p3;
wire   [63:0] p_Result_112_fu_581_p5;
wire   [31:0] LD_fu_593_p1;
wire   [0:0] icmp_ln1090_fu_310_p2;
wire   [31:0] bitcast_ln766_fu_597_p1;
wire   [23:0] tmp_V_23_fu_614_p3;
reg   [23:0] p_Result_70_fu_619_p4;
wire   [24:0] p_Result_114_fu_629_p3;
wire  signed [31:0] sext_ln1198_2_fu_637_p1;
reg   [31:0] l_3_fu_641_p3;
wire   [31:0] sub_ln1099_3_fu_649_p2;
wire   [31:0] lsb_index_3_fu_659_p2;
wire   [30:0] tmp_39_fu_665_p4;
wire   [4:0] trunc_ln1102_3_fu_681_p1;
wire   [4:0] sub_ln1102_3_fu_685_p2;
wire   [23:0] zext_ln1102_3_fu_691_p1;
wire   [23:0] lshr_ln1102_3_fu_695_p2;
wire   [23:0] p_Result_72_fu_701_p2;
wire   [0:0] icmp_ln1101_3_fu_675_p2;
wire   [0:0] icmp_ln1102_3_fu_707_p2;
wire   [0:0] tmp_40_fu_719_p3;
wire   [23:0] trunc_ln1099_2_fu_655_p1;
wire   [23:0] add_ln1104_2_fu_733_p2;
wire   [0:0] p_Result_73_fu_739_p3;
wire   [0:0] xor_ln1104_3_fu_727_p2;
wire   [0:0] and_ln1104_3_fu_747_p2;
wire   [0:0] a_3_fu_713_p2;
wire   [0:0] or_ln1104_fu_753_p2;
wire   [31:0] add_ln1113_2_fu_777_p2;
wire   [63:0] zext_ln1112_2_fu_767_p1;
wire   [63:0] zext_ln1113_2_fu_783_p1;
wire   [31:0] sub_ln1114_1_fu_793_p2;
wire   [63:0] zext_ln1114_2_fu_799_p1;
wire   [0:0] icmp_ln1113_2_fu_771_p2;
wire   [63:0] lshr_ln1113_2_fu_787_p2;
wire   [63:0] shl_ln1114_2_fu_803_p2;
wire   [1:0] or_ln1104_3_fu_759_p3;
wire   [63:0] m_19_fu_809_p3;
wire   [63:0] zext_ln1116_3_fu_817_p1;
wire   [63:0] m_20_fu_821_p2;
wire   [62:0] m_fu_827_p4;
wire   [0:0] p_Result_74_fu_841_p3;
wire   [7:0] trunc_ln1098_3_fu_857_p1;
wire   [7:0] sub_ln1119_3_fu_861_p2;
wire   [7:0] select_ln1098_3_fu_849_p3;
wire   [7:0] add_ln1124_3_fu_867_p2;
wire   [63:0] zext_ln1117_2_fu_837_p1;
wire   [8:0] tmp_5_fu_873_p3;
wire   [63:0] p_Result_115_fu_880_p5;
wire   [31:0] LD_7_fu_892_p1;
wire   [0:0] icmp_ln1090_3_fu_609_p2;
wire   [31:0] bitcast_ln766_2_fu_896_p1;
wire   [23:0] tmp_V_24_fu_913_p3;
reg   [23:0] p_Result_77_fu_918_p4;
wire   [24:0] p_Result_117_fu_928_p3;
wire  signed [31:0] sext_ln1198_3_fu_936_p1;
reg   [31:0] l_4_fu_940_p3;
wire   [31:0] sub_ln1099_4_fu_948_p2;
wire   [31:0] lsb_index_4_fu_958_p2;
wire   [30:0] tmp_43_fu_964_p4;
wire   [4:0] trunc_ln1102_4_fu_980_p1;
wire   [4:0] sub_ln1102_4_fu_984_p2;
wire   [23:0] zext_ln1102_4_fu_990_p1;
wire   [23:0] lshr_ln1102_4_fu_994_p2;
wire   [23:0] p_Result_79_fu_1000_p2;
wire   [0:0] icmp_ln1101_4_fu_974_p2;
wire   [0:0] icmp_ln1102_4_fu_1006_p2;
wire   [0:0] tmp_44_fu_1018_p3;
wire   [23:0] trunc_ln1099_3_fu_954_p1;
wire   [23:0] add_ln1104_3_fu_1032_p2;
wire   [0:0] p_Result_80_fu_1038_p3;
wire   [0:0] xor_ln1104_4_fu_1026_p2;
wire   [0:0] and_ln1104_4_fu_1046_p2;
wire   [0:0] a_4_fu_1012_p2;
wire   [0:0] or_ln1104_9_fu_1052_p2;
wire   [31:0] add_ln1113_3_fu_1076_p2;
wire   [63:0] zext_ln1112_3_fu_1066_p1;
wire   [63:0] zext_ln1113_3_fu_1082_p1;
wire   [31:0] sub_ln1114_2_fu_1092_p2;
wire   [63:0] zext_ln1114_3_fu_1098_p1;
wire   [0:0] icmp_ln1113_3_fu_1070_p2;
wire   [63:0] lshr_ln1113_3_fu_1086_p2;
wire   [63:0] shl_ln1114_3_fu_1102_p2;
wire   [1:0] or_ln1104_4_fu_1058_p3;
wire   [63:0] m_24_fu_1108_p3;
wire   [63:0] zext_ln1116_4_fu_1116_p1;
wire   [63:0] m_25_fu_1120_p2;
wire   [62:0] m_40_fu_1126_p4;
wire   [0:0] p_Result_81_fu_1140_p3;
wire   [7:0] trunc_ln1098_4_fu_1156_p1;
wire   [7:0] sub_ln1119_4_fu_1160_p2;
wire   [7:0] select_ln1098_4_fu_1148_p3;
wire   [7:0] add_ln1124_4_fu_1166_p2;
wire   [63:0] zext_ln1117_3_fu_1136_p1;
wire   [8:0] tmp_6_fu_1172_p3;
wire   [63:0] p_Result_118_fu_1179_p5;
wire   [31:0] LD_8_fu_1191_p1;
wire   [0:0] icmp_ln1090_4_fu_908_p2;
wire   [31:0] bitcast_ln766_3_fu_1195_p1;
wire   [23:0] tmp_V_25_fu_1212_p3;
reg   [23:0] p_Result_84_fu_1217_p4;
wire   [24:0] p_Result_120_fu_1227_p3;
wire  signed [31:0] sext_ln1198_4_fu_1235_p1;
reg   [31:0] l_5_fu_1239_p3;
wire   [31:0] sub_ln1099_5_fu_1247_p2;
wire   [31:0] lsb_index_5_fu_1257_p2;
wire   [30:0] tmp_47_fu_1263_p4;
wire   [4:0] trunc_ln1102_5_fu_1279_p1;
wire   [4:0] sub_ln1102_5_fu_1283_p2;
wire   [23:0] zext_ln1102_5_fu_1289_p1;
wire   [23:0] lshr_ln1102_5_fu_1293_p2;
wire   [23:0] p_Result_86_fu_1299_p2;
wire   [0:0] icmp_ln1101_5_fu_1273_p2;
wire   [0:0] icmp_ln1102_5_fu_1305_p2;
wire   [0:0] tmp_48_fu_1317_p3;
wire   [23:0] trunc_ln1099_4_fu_1253_p1;
wire   [23:0] add_ln1104_4_fu_1331_p2;
wire   [0:0] p_Result_87_fu_1337_p3;
wire   [0:0] xor_ln1104_5_fu_1325_p2;
wire   [0:0] and_ln1104_5_fu_1345_p2;
wire   [0:0] a_5_fu_1311_p2;
wire   [0:0] or_ln1104_10_fu_1351_p2;
wire   [31:0] add_ln1113_4_fu_1375_p2;
wire   [63:0] zext_ln1112_4_fu_1365_p1;
wire   [63:0] zext_ln1113_4_fu_1381_p1;
wire   [31:0] sub_ln1114_3_fu_1391_p2;
wire   [63:0] zext_ln1114_4_fu_1397_p1;
wire   [0:0] icmp_ln1113_4_fu_1369_p2;
wire   [63:0] lshr_ln1113_4_fu_1385_p2;
wire   [63:0] shl_ln1114_4_fu_1401_p2;
wire   [1:0] or_ln1104_5_fu_1357_p3;
wire   [63:0] m_28_fu_1407_p3;
wire   [63:0] zext_ln1116_5_fu_1415_p1;
wire   [63:0] m_29_fu_1419_p2;
wire   [62:0] m_41_fu_1425_p4;
wire   [0:0] p_Result_88_fu_1439_p3;
wire   [7:0] trunc_ln1098_5_fu_1455_p1;
wire   [7:0] sub_ln1119_5_fu_1459_p2;
wire   [7:0] select_ln1098_5_fu_1447_p3;
wire   [7:0] add_ln1124_5_fu_1465_p2;
wire   [63:0] zext_ln1117_4_fu_1435_p1;
wire   [8:0] tmp_7_fu_1471_p3;
wire   [63:0] p_Result_121_fu_1478_p5;
wire   [31:0] LD_9_fu_1490_p1;
wire   [0:0] icmp_ln1090_5_fu_1207_p2;
wire   [31:0] bitcast_ln766_4_fu_1494_p1;
wire   [23:0] tmp_V_26_fu_1511_p3;
reg   [23:0] p_Result_91_fu_1516_p4;
wire   [24:0] p_Result_123_fu_1526_p3;
wire  signed [31:0] sext_ln1198_5_fu_1534_p1;
reg   [31:0] l_6_fu_1538_p3;
wire   [31:0] sub_ln1099_6_fu_1546_p2;
wire   [31:0] lsb_index_6_fu_1556_p2;
wire   [30:0] tmp_51_fu_1562_p4;
wire   [4:0] trunc_ln1102_6_fu_1578_p1;
wire   [4:0] sub_ln1102_6_fu_1582_p2;
wire   [23:0] zext_ln1102_6_fu_1588_p1;
wire   [23:0] lshr_ln1102_6_fu_1592_p2;
wire   [23:0] p_Result_93_fu_1598_p2;
wire   [0:0] icmp_ln1101_6_fu_1572_p2;
wire   [0:0] icmp_ln1102_6_fu_1604_p2;
wire   [0:0] tmp_52_fu_1616_p3;
wire   [23:0] trunc_ln1099_5_fu_1552_p1;
wire   [23:0] add_ln1104_5_fu_1630_p2;
wire   [0:0] p_Result_94_fu_1636_p3;
wire   [0:0] xor_ln1104_6_fu_1624_p2;
wire   [0:0] and_ln1104_6_fu_1644_p2;
wire   [0:0] a_6_fu_1610_p2;
wire   [0:0] or_ln1104_11_fu_1650_p2;
wire   [31:0] add_ln1113_5_fu_1674_p2;
wire   [63:0] zext_ln1112_5_fu_1664_p1;
wire   [63:0] zext_ln1113_5_fu_1680_p1;
wire   [31:0] sub_ln1114_4_fu_1690_p2;
wire   [63:0] zext_ln1114_5_fu_1696_p1;
wire   [0:0] icmp_ln1113_5_fu_1668_p2;
wire   [63:0] lshr_ln1113_5_fu_1684_p2;
wire   [63:0] shl_ln1114_5_fu_1700_p2;
wire   [1:0] or_ln1104_6_fu_1656_p3;
wire   [63:0] m_32_fu_1706_p3;
wire   [63:0] zext_ln1116_6_fu_1714_p1;
wire   [63:0] m_33_fu_1718_p2;
wire   [62:0] m_42_fu_1724_p4;
wire   [0:0] p_Result_95_fu_1738_p3;
wire   [7:0] trunc_ln1098_6_fu_1754_p1;
wire   [7:0] sub_ln1119_6_fu_1758_p2;
wire   [7:0] select_ln1098_6_fu_1746_p3;
wire   [7:0] add_ln1124_6_fu_1764_p2;
wire   [63:0] zext_ln1117_5_fu_1734_p1;
wire   [8:0] tmp_8_fu_1770_p3;
wire   [63:0] p_Result_124_fu_1777_p5;
wire   [31:0] LD_10_fu_1789_p1;
wire   [0:0] icmp_ln1090_6_fu_1506_p2;
wire   [31:0] bitcast_ln766_5_fu_1793_p1;
wire   [23:0] tmp_V_27_fu_1810_p3;
reg   [23:0] p_Result_98_fu_1815_p4;
wire   [24:0] p_Result_126_fu_1825_p3;
wire  signed [31:0] sext_ln1198_6_fu_1833_p1;
reg   [31:0] l_7_fu_1837_p3;
wire   [31:0] sub_ln1099_7_fu_1845_p2;
wire   [31:0] lsb_index_7_fu_1855_p2;
wire   [30:0] tmp_55_fu_1861_p4;
wire   [4:0] trunc_ln1102_7_fu_1877_p1;
wire   [4:0] sub_ln1102_7_fu_1881_p2;
wire   [23:0] zext_ln1102_7_fu_1887_p1;
wire   [23:0] lshr_ln1102_7_fu_1891_p2;
wire   [23:0] p_Result_100_fu_1897_p2;
wire   [0:0] icmp_ln1101_7_fu_1871_p2;
wire   [0:0] icmp_ln1102_7_fu_1903_p2;
wire   [0:0] tmp_56_fu_1915_p3;
wire   [23:0] trunc_ln1099_6_fu_1851_p1;
wire   [23:0] add_ln1104_6_fu_1929_p2;
wire   [0:0] p_Result_101_fu_1935_p3;
wire   [0:0] xor_ln1104_7_fu_1923_p2;
wire   [0:0] and_ln1104_7_fu_1943_p2;
wire   [0:0] a_7_fu_1909_p2;
wire   [0:0] or_ln1104_12_fu_1949_p2;
wire   [31:0] add_ln1113_6_fu_1973_p2;
wire   [63:0] zext_ln1112_6_fu_1963_p1;
wire   [63:0] zext_ln1113_6_fu_1979_p1;
wire   [31:0] sub_ln1114_5_fu_1989_p2;
wire   [63:0] zext_ln1114_6_fu_1995_p1;
wire   [0:0] icmp_ln1113_6_fu_1967_p2;
wire   [63:0] lshr_ln1113_6_fu_1983_p2;
wire   [63:0] shl_ln1114_6_fu_1999_p2;
wire   [1:0] or_ln1104_7_fu_1955_p3;
wire   [63:0] m_36_fu_2005_p3;
wire   [63:0] zext_ln1116_7_fu_2013_p1;
wire   [63:0] m_37_fu_2017_p2;
wire   [62:0] m_43_fu_2023_p4;
wire   [0:0] p_Result_102_fu_2037_p3;
wire   [7:0] trunc_ln1098_7_fu_2053_p1;
wire   [7:0] sub_ln1119_7_fu_2057_p2;
wire   [7:0] select_ln1098_7_fu_2045_p3;
wire   [7:0] add_ln1124_7_fu_2063_p2;
wire   [63:0] zext_ln1117_6_fu_2033_p1;
wire   [8:0] tmp_9_fu_2069_p3;
wire   [63:0] p_Result_127_fu_2076_p5;
wire   [31:0] LD_11_fu_2088_p1;
wire   [0:0] icmp_ln1090_7_fu_1805_p2;
wire   [31:0] bitcast_ln766_6_fu_2092_p1;
wire   [31:0] bitcast_ln200_fu_2104_p1;
wire   [7:0] tmp_fu_2107_p4;
wire   [22:0] trunc_ln200_fu_2117_p1;
wire   [0:0] icmp_ln200_2_fu_2127_p2;
wire   [0:0] icmp_ln200_fu_2121_p2;
wire   [0:0] or_ln200_fu_2133_p2;
wire   [0:0] grp_fu_206_p2;
wire   [0:0] and_ln200_fu_2139_p2;
wire   [31:0] bitcast_ln200_1_fu_2152_p1;
wire   [7:0] tmp_3_fu_2155_p4;
wire   [22:0] trunc_ln200_1_fu_2165_p1;
wire   [0:0] icmp_ln200_4_fu_2175_p2;
wire   [0:0] icmp_ln200_3_fu_2169_p2;
wire   [0:0] or_ln200_1_fu_2181_p2;
wire   [0:0] grp_fu_211_p2;
wire   [0:0] and_ln200_1_fu_2187_p2;
wire   [31:0] bitcast_ln224_fu_2200_p1;
wire   [7:0] tmp_1_fu_2203_p4;
wire   [22:0] trunc_ln224_fu_2213_p1;
wire   [31:0] bitcast_ln224_1_fu_2229_p1;
wire   [7:0] tmp_11_fu_2232_p4;
wire   [22:0] trunc_ln224_2_fu_2242_p1;
wire   [0:0] or_ln224_fu_2258_p2;
wire   [0:0] or_ln224_1_fu_2267_p2;
wire   [0:0] and_ln224_fu_2262_p2;
wire   [31:0] bitcast_ln317_fu_2276_p1;
wire   [31:0] data_V_fu_2279_p3;
wire   [22:0] p_Result_129_fu_2305_p1;
wire   [24:0] mantissa_fu_2309_p4;
wire   [7:0] xs_exp_V_fu_2295_p4;
wire   [8:0] zext_ln346_fu_2323_p1;
wire   [8:0] add_ln346_fu_2327_p2;
wire   [7:0] sub_ln1512_fu_2341_p2;
wire   [0:0] isNeg_fu_2333_p3;
wire  signed [8:0] sext_ln1512_fu_2347_p1;
wire   [8:0] ush_fu_2351_p3;
wire  signed [31:0] sext_ln1488_fu_2359_p1;
wire   [78:0] zext_ln15_fu_2319_p1;
wire   [78:0] zext_ln1488_fu_2363_p1;
wire   [78:0] r_V_fu_2367_p2;
wire   [0:0] tmp_61_fu_2379_p3;
wire   [78:0] r_V_48_fu_2373_p2;
wire   [7:0] zext_ln818_fu_2387_p1;
wire   [7:0] tmp_14_fu_2391_p4;
wire   [7:0] val_fu_2401_p3;
wire   [0:0] p_Result_128_fu_2287_p3;
wire   [7:0] result_V_11_fu_2409_p2;
wire   [7:0] result_V_fu_2415_p3;
wire   [0:0] and_ln224_1_fu_2271_p2;
wire   [31:0] bitcast_ln317_1_fu_2427_p1;
wire   [31:0] data_V_2_fu_2430_p3;
wire   [22:0] p_Result_131_fu_2456_p1;
wire   [24:0] mantissa_2_fu_2460_p4;
wire   [7:0] xs_exp_V_2_fu_2446_p4;
wire   [8:0] zext_ln346_2_fu_2474_p1;
wire   [8:0] add_ln346_2_fu_2478_p2;
wire   [7:0] sub_ln1512_2_fu_2492_p2;
wire   [0:0] isNeg_2_fu_2484_p3;
wire  signed [8:0] sext_ln1512_2_fu_2498_p1;
wire   [8:0] ush_2_fu_2502_p3;
wire  signed [31:0] sext_ln1488_2_fu_2510_p1;
wire   [78:0] zext_ln15_2_fu_2470_p1;
wire   [78:0] zext_ln1488_2_fu_2514_p1;
wire   [78:0] r_V_49_fu_2518_p2;
wire   [0:0] tmp_65_fu_2530_p3;
wire   [78:0] r_V_50_fu_2524_p2;
wire   [7:0] zext_ln818_2_fu_2538_p1;
wire   [7:0] tmp_15_fu_2542_p4;
wire   [7:0] val_2_fu_2552_p3;
wire   [0:0] p_Result_130_fu_2438_p3;
wire   [7:0] result_V_14_fu_2560_p2;
wire   [7:0] result_V_15_fu_2566_p3;
wire   [7:0] sub_ln101_fu_2584_p2;
wire   [7:0] sub_ln100_fu_2578_p2;
wire   [7:0] t_9_fu_2598_p3;
wire   [7:0] select_ln99_fu_2590_p3;
wire   [0:0] tmp_69_fu_2646_p3;
wire   [0:0] tmp_68_fu_2638_p3;
wire   [1:0] select_ln95_1_fu_2658_p3;
wire   [1:0] zext_ln95_fu_2654_p1;
wire   [1:0] zext_ln93_fu_2672_p1;
wire   [1:0] select_ln95_fu_2675_p3;
wire   [7:0] sub_ln101_1_fu_2693_p2;
wire   [7:0] sub_ln100_1_fu_2688_p2;
wire   [7:0] t_10_fu_2704_p3;
wire   [7:0] select_ln99_2_fu_2698_p3;
wire   [7:0] select_ln93_3_fu_2716_p3;
wire   [7:0] select_ln93_2_fu_2710_p3;
wire   [0:0] tmp_73_fu_2746_p3;
wire   [0:0] tmp_72_fu_2738_p3;
wire   [1:0] select_ln95_2_fu_2758_p3;
wire   [1:0] zext_ln95_1_fu_2754_p1;
wire   [0:0] tmp_70_fu_2722_p3;
wire   [7:0] sub_ln101_2_fu_2778_p2;
wire   [7:0] sub_ln100_2_fu_2772_p2;
wire   [0:0] tmp_71_fu_2730_p3;
wire   [7:0] t_11_fu_2792_p3;
wire   [7:0] select_ln99_4_fu_2784_p3;
wire   [7:0] select_ln93_5_fu_2808_p3;
wire   [7:0] select_ln93_4_fu_2800_p3;
wire   [0:0] tmp_77_fu_2840_p3;
wire   [0:0] tmp_76_fu_2832_p3;
wire   [1:0] select_ln95_3_fu_2852_p3;
wire   [1:0] zext_ln95_2_fu_2848_p1;
wire   [0:0] tmp_74_fu_2816_p3;
wire   [7:0] sub_ln101_3_fu_2872_p2;
wire   [7:0] sub_ln100_3_fu_2866_p2;
wire   [0:0] tmp_75_fu_2824_p3;
wire   [7:0] t_12_fu_2886_p3;
wire   [7:0] select_ln99_6_fu_2878_p3;
wire   [7:0] select_ln93_7_fu_2902_p3;
wire   [7:0] select_ln93_6_fu_2894_p3;
wire   [0:0] tmp_81_fu_2934_p3;
wire   [0:0] tmp_80_fu_2926_p3;
wire   [1:0] select_ln95_4_fu_2946_p3;
wire   [1:0] zext_ln95_3_fu_2942_p1;
wire   [0:0] tmp_78_fu_2910_p3;
wire   [7:0] sub_ln101_4_fu_2966_p2;
wire   [7:0] sub_ln100_4_fu_2960_p2;
wire   [0:0] tmp_79_fu_2918_p3;
wire   [7:0] t_13_fu_2980_p3;
wire   [7:0] select_ln99_8_fu_2972_p3;
wire   [7:0] select_ln93_9_fu_2996_p3;
wire   [7:0] select_ln93_8_fu_2988_p3;
wire   [0:0] tmp_85_fu_3028_p3;
wire   [0:0] tmp_84_fu_3020_p3;
wire   [1:0] select_ln95_5_fu_3040_p3;
wire   [1:0] zext_ln95_4_fu_3036_p1;
wire   [0:0] tmp_82_fu_3004_p3;
wire   [7:0] sub_ln101_5_fu_3060_p2;
wire   [7:0] sub_ln100_5_fu_3054_p2;
wire   [0:0] tmp_83_fu_3012_p3;
wire   [7:0] t_14_fu_3074_p3;
wire   [7:0] select_ln99_10_fu_3066_p3;
wire   [7:0] select_ln93_11_fu_3090_p3;
wire   [7:0] select_ln93_10_fu_3082_p3;
wire   [0:0] tmp_89_fu_3122_p3;
wire   [0:0] tmp_88_fu_3114_p3;
wire   [1:0] select_ln95_6_fu_3134_p3;
wire   [1:0] zext_ln95_5_fu_3130_p1;
wire   [7:0] sub_ln101_6_fu_3154_p2;
wire   [0:0] tmp_86_fu_3098_p3;
wire   [0:0] tmp_90_fu_3160_p3;
wire   [0:0] tmp_91_fu_3168_p3;
wire   [0:0] tmp_87_fu_3106_p3;
wire   [0:0] tmp_92_fu_3184_p3;
wire   [0:0] select_ln99_12_fu_3176_p3;
wire   [7:0] sub_ln100_6_fu_3148_p2;
wire   [0:0] tmp_93_fu_3200_p3;
wire   [0:0] select_ln99_13_fu_3208_p3;
wire   [0:0] select_ln93_13_fu_3216_p3;
wire   [0:0] select_ln93_12_fu_3192_p3;
wire   [1:0] select_ln95_7_fu_3228_p3;
wire   [1:0] zext_ln95_6_fu_3224_p1;
wire   [1:0] xor_ln95_7_fu_3236_p2;
wire   [1:0] xor_ln95_6_fu_3142_p2;
wire   [1:0] xor_ln95_5_fu_3048_p2;
wire   [1:0] xor_ln95_4_fu_2954_p2;
wire   [1:0] xor_ln95_3_fu_2860_p2;
wire   [1:0] xor_ln95_2_fu_2766_p2;
wire   [1:0] xor_ln95_fu_2682_p2;
wire    ap_block_pp0_stage0_00001;
reg   [23:0] x_int_reg;
reg   [23:0] y_int_reg;
reg   [23:0] x_min_int_reg;
reg   [23:0] y_min_int_reg;
reg   [23:0] x_max_int_reg;
reg   [23:0] y_max_int_reg;
wire    ap_ce_reg;

tri2d_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_f_reg_3363),
    .din1(xmin_f_reg_3373),
    .ce(1'b1),
    .dout(grp_fu_172_p2)
);

tri2d_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(xmax_f_reg_3385),
    .din1(xmin_f_reg_3373),
    .ce(1'b1),
    .dout(grp_fu_176_p2)
);

tri2d_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(y_f_reg_3368),
    .din1(ymin_f_reg_3379),
    .ce(1'b1),
    .dout(grp_fu_180_p2)
);

tri2d_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ymax_f_reg_3390),
    .din1(ymin_f_reg_3379),
    .ce(1'b1),
    .dout(grp_fu_184_p2)
);

tri2d_fmul_32ns_32ns_32_3_max_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_x_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln224_reg_3429),
    .din1(32'd1132396544),
    .ce(1'b1),
    .dout(grp_fu_188_p2)
);

tri2d_fmul_32ns_32ns_32_3_max_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_x_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln224_2_reg_3436),
    .din1(32'd1132396544),
    .ce(1'b1),
    .dout(grp_fu_193_p2)
);

tri2d_fdiv_32ns_32ns_32_9_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_9_no_dsp_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_reg_3395),
    .din1(sub6_reg_3400),
    .ce(1'b1),
    .dout(grp_fu_198_p2)
);

tri2d_fdiv_32ns_32ns_32_9_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_9_no_dsp_1_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub7_reg_3405),
    .din1(sub8_reg_3410),
    .ce(1'b1),
    .dout(grp_fu_202_p2)
);

tri2d_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(div_reg_3415),
    .din1(32'd1065353216),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_206_p2)
);

tri2d_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(div9_reg_3422),
    .din1(32'd1065353216),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_211_p2)
);

tri2d_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln224_reg_3429),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_216_p2)
);

tri2d_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln224_2_reg_3436),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_221_p2)
);

always @ (posedge ap_clk) begin
    x_int_reg <= x;
end

always @ (posedge ap_clk) begin
    x_max_int_reg <= x_max;
end

always @ (posedge ap_clk) begin
    x_min_int_reg <= x_min;
end

always @ (posedge ap_clk) begin
    y_int_reg <= y;
end

always @ (posedge ap_clk) begin
    y_max_int_reg <= y_max;
end

always @ (posedge ap_clk) begin
    y_min_int_reg <= y_min;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        div9_reg_3422 <= grp_fu_202_p2;
        div9_reg_3422_pp0_iter15_reg <= div9_reg_3422;
        div_reg_3415 <= grp_fu_198_p2;
        div_reg_3415_pp0_iter15_reg <= div_reg_3415;
        icmp_ln224_2_reg_3448 <= icmp_ln224_2_fu_2223_p2;
        icmp_ln224_2_reg_3448_pp0_iter18_reg <= icmp_ln224_2_reg_3448;
        icmp_ln224_2_reg_3448_pp0_iter19_reg <= icmp_ln224_2_reg_3448_pp0_iter18_reg;
        icmp_ln224_3_reg_3453 <= icmp_ln224_3_fu_2246_p2;
        icmp_ln224_3_reg_3453_pp0_iter18_reg <= icmp_ln224_3_reg_3453;
        icmp_ln224_3_reg_3453_pp0_iter19_reg <= icmp_ln224_3_reg_3453_pp0_iter18_reg;
        icmp_ln224_4_reg_3458 <= icmp_ln224_4_fu_2252_p2;
        icmp_ln224_4_reg_3458_pp0_iter18_reg <= icmp_ln224_4_reg_3458;
        icmp_ln224_4_reg_3458_pp0_iter19_reg <= icmp_ln224_4_reg_3458_pp0_iter18_reg;
        icmp_ln224_reg_3443 <= icmp_ln224_fu_2217_p2;
        icmp_ln224_reg_3443_pp0_iter18_reg <= icmp_ln224_reg_3443;
        icmp_ln224_reg_3443_pp0_iter19_reg <= icmp_ln224_reg_3443_pp0_iter18_reg;
        p_Result_110_reg_3297 <= x_int_reg[32'd23];
        p_Result_113_reg_3308 <= y_int_reg[32'd23];
        p_Result_116_reg_3319 <= x_min_int_reg[32'd23];
        p_Result_119_reg_3330 <= y_min_int_reg[32'd23];
        p_Result_122_reg_3341 <= x_max_int_reg[32'd23];
        p_Result_125_reg_3352 <= y_max_int_reg[32'd23];
        retval_0_i1248_op_reg_3473 <= grp_fu_188_p2;
        retval_0_i1650_op_reg_3478 <= grp_fu_193_p2;
        rx_reg_3483 <= rx_fu_2423_p1;
        ry_reg_3488 <= ry_fu_2574_p1;
        select_ln224_2_reg_3436 <= select_ln224_2_fu_2193_p3;
        select_ln224_reg_3429 <= select_ln224_fu_2145_p3;
        select_ln93_1_reg_3500 <= select_ln93_1_fu_2614_p3;
        select_ln93_reg_3493 <= select_ln93_fu_2606_p3;
        sub6_reg_3400 <= grp_fu_176_p2;
        sub7_reg_3405 <= grp_fu_180_p2;
        sub8_reg_3410 <= grp_fu_184_p2;
        sub_reg_3395 <= grp_fu_172_p2;
        tmp_12_reg_3468 <= grp_fu_221_p2;
        tmp_12_reg_3468_pp0_iter19_reg <= tmp_12_reg_3468;
        tmp_2_reg_3463 <= grp_fu_216_p2;
        tmp_2_reg_3463_pp0_iter19_reg <= tmp_2_reg_3463;
        tmp_66_reg_3507 <= select_ln93_1_fu_2614_p3[32'd1];
        tmp_67_reg_3513 <= select_ln93_fu_2606_p3[32'd1];
        tmp_V_12_reg_3314 <= tmp_V_12_fu_248_p2;
        tmp_V_14_reg_3325 <= tmp_V_14_fu_262_p2;
        tmp_V_16_reg_3336 <= tmp_V_16_fu_276_p2;
        tmp_V_18_reg_3347 <= tmp_V_18_fu_290_p2;
        tmp_V_20_reg_3358 <= tmp_V_20_fu_304_p2;
        tmp_V_reg_3303 <= tmp_V_fu_234_p2;
        x_f_reg_3363 <= x_f_fu_601_p3;
        x_max_read_reg_3267 <= x_max_int_reg;
        x_min_read_reg_3279 <= x_min_int_reg;
        x_read_reg_3291 <= x_int_reg;
        xmax_f_reg_3385 <= xmax_f_fu_1797_p3;
        xmin_f_reg_3373 <= xmin_f_fu_1199_p3;
        xor_ln95_1_reg_3519 <= xor_ln95_1_fu_2666_p2;
        y_f_reg_3368 <= y_f_fu_900_p3;
        y_max_read_reg_3261 <= y_max_int_reg;
        y_min_read_reg_3273 <= y_min_int_reg;
        y_read_reg_3285 <= y_int_reg;
        ymax_f_reg_3390 <= ymax_f_fu_2096_p3;
        ymin_f_reg_3379 <= ymin_f_fu_1498_p3;
    end
end

assign LD_10_fu_1789_p1 = p_Result_124_fu_1777_p5[31:0];

assign LD_11_fu_2088_p1 = p_Result_127_fu_2076_p5[31:0];

assign LD_7_fu_892_p1 = p_Result_115_fu_880_p5[31:0];

assign LD_8_fu_1191_p1 = p_Result_118_fu_1179_p5[31:0];

assign LD_9_fu_1490_p1 = p_Result_121_fu_1478_p5[31:0];

assign LD_fu_593_p1 = p_Result_112_fu_581_p5[31:0];

assign a_3_fu_713_p2 = (icmp_ln1102_3_fu_707_p2 & icmp_ln1101_3_fu_675_p2);

assign a_4_fu_1012_p2 = (icmp_ln1102_4_fu_1006_p2 & icmp_ln1101_4_fu_974_p2);

assign a_5_fu_1311_p2 = (icmp_ln1102_5_fu_1305_p2 & icmp_ln1101_5_fu_1273_p2);

assign a_6_fu_1610_p2 = (icmp_ln1102_6_fu_1604_p2 & icmp_ln1101_6_fu_1572_p2);

assign a_7_fu_1909_p2 = (icmp_ln1102_7_fu_1903_p2 & icmp_ln1101_7_fu_1871_p2);

assign a_fu_414_p2 = (icmp_ln1102_fu_408_p2 & icmp_ln1101_fu_376_p2);

assign add_ln1104_2_fu_733_p2 = ($signed(trunc_ln1099_2_fu_655_p1) + $signed(24'd16777192));

assign add_ln1104_3_fu_1032_p2 = ($signed(trunc_ln1099_3_fu_954_p1) + $signed(24'd16777192));

assign add_ln1104_4_fu_1331_p2 = ($signed(trunc_ln1099_4_fu_1253_p1) + $signed(24'd16777192));

assign add_ln1104_5_fu_1630_p2 = ($signed(trunc_ln1099_5_fu_1552_p1) + $signed(24'd16777192));

assign add_ln1104_6_fu_1929_p2 = ($signed(trunc_ln1099_6_fu_1851_p1) + $signed(24'd16777192));

assign add_ln1104_fu_434_p2 = ($signed(trunc_ln1099_fu_356_p1) + $signed(24'd16777192));

assign add_ln1113_2_fu_777_p2 = ($signed(sub_ln1099_3_fu_649_p2) + $signed(32'd4294967271));

assign add_ln1113_3_fu_1076_p2 = ($signed(sub_ln1099_4_fu_948_p2) + $signed(32'd4294967271));

assign add_ln1113_4_fu_1375_p2 = ($signed(sub_ln1099_5_fu_1247_p2) + $signed(32'd4294967271));

assign add_ln1113_5_fu_1674_p2 = ($signed(sub_ln1099_6_fu_1546_p2) + $signed(32'd4294967271));

assign add_ln1113_6_fu_1973_p2 = ($signed(sub_ln1099_7_fu_1845_p2) + $signed(32'd4294967271));

assign add_ln1113_fu_478_p2 = ($signed(sub_ln1099_fu_350_p2) + $signed(32'd4294967271));

assign add_ln1124_3_fu_867_p2 = (sub_ln1119_3_fu_861_p2 + select_ln1098_3_fu_849_p3);

assign add_ln1124_4_fu_1166_p2 = (sub_ln1119_4_fu_1160_p2 + select_ln1098_4_fu_1148_p3);

assign add_ln1124_5_fu_1465_p2 = (sub_ln1119_5_fu_1459_p2 + select_ln1098_5_fu_1447_p3);

assign add_ln1124_6_fu_1764_p2 = (sub_ln1119_6_fu_1758_p2 + select_ln1098_6_fu_1746_p3);

assign add_ln1124_7_fu_2063_p2 = (sub_ln1119_7_fu_2057_p2 + select_ln1098_7_fu_2045_p3);

assign add_ln1124_fu_568_p2 = (sub_ln1119_fu_562_p2 + select_ln1098_fu_550_p3);

assign add_ln346_2_fu_2478_p2 = ($signed(zext_ln346_2_fu_2474_p1) + $signed(9'd385));

assign add_ln346_fu_2327_p2 = ($signed(zext_ln346_fu_2323_p1) + $signed(9'd385));

assign and_ln1104_3_fu_747_p2 = (xor_ln1104_3_fu_727_p2 & p_Result_73_fu_739_p3);

assign and_ln1104_4_fu_1046_p2 = (xor_ln1104_4_fu_1026_p2 & p_Result_80_fu_1038_p3);

assign and_ln1104_5_fu_1345_p2 = (xor_ln1104_5_fu_1325_p2 & p_Result_87_fu_1337_p3);

assign and_ln1104_6_fu_1644_p2 = (xor_ln1104_6_fu_1624_p2 & p_Result_94_fu_1636_p3);

assign and_ln1104_7_fu_1943_p2 = (xor_ln1104_7_fu_1923_p2 & p_Result_101_fu_1935_p3);

assign and_ln1104_fu_448_p2 = (xor_ln1104_fu_428_p2 & p_Result_66_fu_440_p3);

assign and_ln200_1_fu_2187_p2 = (or_ln200_1_fu_2181_p2 & grp_fu_211_p2);

assign and_ln200_fu_2139_p2 = (or_ln200_fu_2133_p2 & grp_fu_206_p2);

assign and_ln224_1_fu_2271_p2 = (tmp_12_reg_3468_pp0_iter19_reg & or_ln224_1_fu_2267_p2);

assign and_ln224_fu_2262_p2 = (tmp_2_reg_3463_pp0_iter19_reg & or_ln224_fu_2258_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_return = {{{{{{{{xor_ln95_7_fu_3236_p2}, {xor_ln95_6_fu_3142_p2}}, {xor_ln95_5_fu_3048_p2}}, {xor_ln95_4_fu_2954_p2}}, {xor_ln95_3_fu_2860_p2}}, {xor_ln95_2_fu_2766_p2}}, {xor_ln95_1_reg_3519}}, {xor_ln95_fu_2682_p2}};

assign bitcast_ln200_1_fu_2152_p1 = div9_reg_3422_pp0_iter15_reg;

assign bitcast_ln200_fu_2104_p1 = div_reg_3415_pp0_iter15_reg;

assign bitcast_ln224_1_fu_2229_p1 = select_ln224_2_reg_3436;

assign bitcast_ln224_fu_2200_p1 = select_ln224_reg_3429;

assign bitcast_ln317_1_fu_2427_p1 = retval_0_i1650_op_reg_3478;

assign bitcast_ln317_fu_2276_p1 = retval_0_i1248_op_reg_3473;

assign bitcast_ln766_2_fu_896_p1 = LD_7_fu_892_p1;

assign bitcast_ln766_3_fu_1195_p1 = LD_8_fu_1191_p1;

assign bitcast_ln766_4_fu_1494_p1 = LD_9_fu_1490_p1;

assign bitcast_ln766_5_fu_1793_p1 = LD_10_fu_1789_p1;

assign bitcast_ln766_6_fu_2092_p1 = LD_11_fu_2088_p1;

assign bitcast_ln766_fu_597_p1 = LD_fu_593_p1;

assign data_V_2_fu_2430_p3 = ((and_ln224_1_fu_2271_p2[0:0] == 1'b1) ? bitcast_ln317_1_fu_2427_p1 : 32'd0);

assign data_V_fu_2279_p3 = ((and_ln224_fu_2262_p2[0:0] == 1'b1) ? bitcast_ln317_fu_2276_p1 : 32'd0);

assign icmp_ln1090_3_fu_609_p2 = ((y_read_reg_3285 == 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1090_4_fu_908_p2 = ((x_min_read_reg_3279 == 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1090_5_fu_1207_p2 = ((y_min_read_reg_3273 == 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1090_6_fu_1506_p2 = ((x_max_read_reg_3267 == 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1090_7_fu_1805_p2 = ((y_max_read_reg_3261 == 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1090_fu_310_p2 = ((x_read_reg_3291 == 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1101_3_fu_675_p2 = (($signed(tmp_39_fu_665_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1101_4_fu_974_p2 = (($signed(tmp_43_fu_964_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1101_5_fu_1273_p2 = (($signed(tmp_47_fu_1263_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1101_6_fu_1572_p2 = (($signed(tmp_51_fu_1562_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1101_7_fu_1871_p2 = (($signed(tmp_55_fu_1861_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1101_fu_376_p2 = (($signed(tmp_35_fu_366_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1102_3_fu_707_p2 = ((p_Result_72_fu_701_p2 != 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1102_4_fu_1006_p2 = ((p_Result_79_fu_1000_p2 != 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1102_5_fu_1305_p2 = ((p_Result_86_fu_1299_p2 != 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1102_6_fu_1604_p2 = ((p_Result_93_fu_1598_p2 != 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1102_7_fu_1903_p2 = ((p_Result_100_fu_1897_p2 != 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1102_fu_408_p2 = ((p_Result_65_fu_402_p2 != 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1113_2_fu_771_p2 = (($signed(lsb_index_3_fu_659_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1113_3_fu_1070_p2 = (($signed(lsb_index_4_fu_958_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1113_4_fu_1369_p2 = (($signed(lsb_index_5_fu_1257_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1113_5_fu_1668_p2 = (($signed(lsb_index_6_fu_1556_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1113_6_fu_1967_p2 = (($signed(lsb_index_7_fu_1855_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1113_fu_472_p2 = (($signed(lsb_index_fu_360_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln200_2_fu_2127_p2 = ((trunc_ln200_fu_2117_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln200_3_fu_2169_p2 = ((tmp_3_fu_2155_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln200_4_fu_2175_p2 = ((trunc_ln200_1_fu_2165_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln200_fu_2121_p2 = ((tmp_fu_2107_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_2_fu_2223_p2 = ((trunc_ln224_fu_2213_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_3_fu_2246_p2 = ((tmp_11_fu_2232_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_4_fu_2252_p2 = ((trunc_ln224_2_fu_2242_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_2217_p2 = ((tmp_1_fu_2203_p4 != 8'd255) ? 1'b1 : 1'b0);

assign isNeg_2_fu_2484_p3 = add_ln346_2_fu_2478_p2[32'd8];

assign isNeg_fu_2333_p3 = add_ln346_fu_2327_p2[32'd8];


always @ (sext_ln1198_2_fu_637_p1) begin
    if (sext_ln1198_2_fu_637_p1[0] == 1'b1) begin
        l_3_fu_641_p3 = 32'd0;
    end else if (sext_ln1198_2_fu_637_p1[1] == 1'b1) begin
        l_3_fu_641_p3 = 32'd1;
    end else if (sext_ln1198_2_fu_637_p1[2] == 1'b1) begin
        l_3_fu_641_p3 = 32'd2;
    end else if (sext_ln1198_2_fu_637_p1[3] == 1'b1) begin
        l_3_fu_641_p3 = 32'd3;
    end else if (sext_ln1198_2_fu_637_p1[4] == 1'b1) begin
        l_3_fu_641_p3 = 32'd4;
    end else if (sext_ln1198_2_fu_637_p1[5] == 1'b1) begin
        l_3_fu_641_p3 = 32'd5;
    end else if (sext_ln1198_2_fu_637_p1[6] == 1'b1) begin
        l_3_fu_641_p3 = 32'd6;
    end else if (sext_ln1198_2_fu_637_p1[7] == 1'b1) begin
        l_3_fu_641_p3 = 32'd7;
    end else if (sext_ln1198_2_fu_637_p1[8] == 1'b1) begin
        l_3_fu_641_p3 = 32'd8;
    end else if (sext_ln1198_2_fu_637_p1[9] == 1'b1) begin
        l_3_fu_641_p3 = 32'd9;
    end else if (sext_ln1198_2_fu_637_p1[10] == 1'b1) begin
        l_3_fu_641_p3 = 32'd10;
    end else if (sext_ln1198_2_fu_637_p1[11] == 1'b1) begin
        l_3_fu_641_p3 = 32'd11;
    end else if (sext_ln1198_2_fu_637_p1[12] == 1'b1) begin
        l_3_fu_641_p3 = 32'd12;
    end else if (sext_ln1198_2_fu_637_p1[13] == 1'b1) begin
        l_3_fu_641_p3 = 32'd13;
    end else if (sext_ln1198_2_fu_637_p1[14] == 1'b1) begin
        l_3_fu_641_p3 = 32'd14;
    end else if (sext_ln1198_2_fu_637_p1[15] == 1'b1) begin
        l_3_fu_641_p3 = 32'd15;
    end else if (sext_ln1198_2_fu_637_p1[16] == 1'b1) begin
        l_3_fu_641_p3 = 32'd16;
    end else if (sext_ln1198_2_fu_637_p1[17] == 1'b1) begin
        l_3_fu_641_p3 = 32'd17;
    end else if (sext_ln1198_2_fu_637_p1[18] == 1'b1) begin
        l_3_fu_641_p3 = 32'd18;
    end else if (sext_ln1198_2_fu_637_p1[19] == 1'b1) begin
        l_3_fu_641_p3 = 32'd19;
    end else if (sext_ln1198_2_fu_637_p1[20] == 1'b1) begin
        l_3_fu_641_p3 = 32'd20;
    end else if (sext_ln1198_2_fu_637_p1[21] == 1'b1) begin
        l_3_fu_641_p3 = 32'd21;
    end else if (sext_ln1198_2_fu_637_p1[22] == 1'b1) begin
        l_3_fu_641_p3 = 32'd22;
    end else if (sext_ln1198_2_fu_637_p1[23] == 1'b1) begin
        l_3_fu_641_p3 = 32'd23;
    end else if (sext_ln1198_2_fu_637_p1[24] == 1'b1) begin
        l_3_fu_641_p3 = 32'd24;
    end else if (sext_ln1198_2_fu_637_p1[25] == 1'b1) begin
        l_3_fu_641_p3 = 32'd25;
    end else if (sext_ln1198_2_fu_637_p1[26] == 1'b1) begin
        l_3_fu_641_p3 = 32'd26;
    end else if (sext_ln1198_2_fu_637_p1[27] == 1'b1) begin
        l_3_fu_641_p3 = 32'd27;
    end else if (sext_ln1198_2_fu_637_p1[28] == 1'b1) begin
        l_3_fu_641_p3 = 32'd28;
    end else if (sext_ln1198_2_fu_637_p1[29] == 1'b1) begin
        l_3_fu_641_p3 = 32'd29;
    end else if (sext_ln1198_2_fu_637_p1[30] == 1'b1) begin
        l_3_fu_641_p3 = 32'd30;
    end else if (sext_ln1198_2_fu_637_p1[31] == 1'b1) begin
        l_3_fu_641_p3 = 32'd31;
    end else begin
        l_3_fu_641_p3 = 32'd32;
    end
end


always @ (sext_ln1198_3_fu_936_p1) begin
    if (sext_ln1198_3_fu_936_p1[0] == 1'b1) begin
        l_4_fu_940_p3 = 32'd0;
    end else if (sext_ln1198_3_fu_936_p1[1] == 1'b1) begin
        l_4_fu_940_p3 = 32'd1;
    end else if (sext_ln1198_3_fu_936_p1[2] == 1'b1) begin
        l_4_fu_940_p3 = 32'd2;
    end else if (sext_ln1198_3_fu_936_p1[3] == 1'b1) begin
        l_4_fu_940_p3 = 32'd3;
    end else if (sext_ln1198_3_fu_936_p1[4] == 1'b1) begin
        l_4_fu_940_p3 = 32'd4;
    end else if (sext_ln1198_3_fu_936_p1[5] == 1'b1) begin
        l_4_fu_940_p3 = 32'd5;
    end else if (sext_ln1198_3_fu_936_p1[6] == 1'b1) begin
        l_4_fu_940_p3 = 32'd6;
    end else if (sext_ln1198_3_fu_936_p1[7] == 1'b1) begin
        l_4_fu_940_p3 = 32'd7;
    end else if (sext_ln1198_3_fu_936_p1[8] == 1'b1) begin
        l_4_fu_940_p3 = 32'd8;
    end else if (sext_ln1198_3_fu_936_p1[9] == 1'b1) begin
        l_4_fu_940_p3 = 32'd9;
    end else if (sext_ln1198_3_fu_936_p1[10] == 1'b1) begin
        l_4_fu_940_p3 = 32'd10;
    end else if (sext_ln1198_3_fu_936_p1[11] == 1'b1) begin
        l_4_fu_940_p3 = 32'd11;
    end else if (sext_ln1198_3_fu_936_p1[12] == 1'b1) begin
        l_4_fu_940_p3 = 32'd12;
    end else if (sext_ln1198_3_fu_936_p1[13] == 1'b1) begin
        l_4_fu_940_p3 = 32'd13;
    end else if (sext_ln1198_3_fu_936_p1[14] == 1'b1) begin
        l_4_fu_940_p3 = 32'd14;
    end else if (sext_ln1198_3_fu_936_p1[15] == 1'b1) begin
        l_4_fu_940_p3 = 32'd15;
    end else if (sext_ln1198_3_fu_936_p1[16] == 1'b1) begin
        l_4_fu_940_p3 = 32'd16;
    end else if (sext_ln1198_3_fu_936_p1[17] == 1'b1) begin
        l_4_fu_940_p3 = 32'd17;
    end else if (sext_ln1198_3_fu_936_p1[18] == 1'b1) begin
        l_4_fu_940_p3 = 32'd18;
    end else if (sext_ln1198_3_fu_936_p1[19] == 1'b1) begin
        l_4_fu_940_p3 = 32'd19;
    end else if (sext_ln1198_3_fu_936_p1[20] == 1'b1) begin
        l_4_fu_940_p3 = 32'd20;
    end else if (sext_ln1198_3_fu_936_p1[21] == 1'b1) begin
        l_4_fu_940_p3 = 32'd21;
    end else if (sext_ln1198_3_fu_936_p1[22] == 1'b1) begin
        l_4_fu_940_p3 = 32'd22;
    end else if (sext_ln1198_3_fu_936_p1[23] == 1'b1) begin
        l_4_fu_940_p3 = 32'd23;
    end else if (sext_ln1198_3_fu_936_p1[24] == 1'b1) begin
        l_4_fu_940_p3 = 32'd24;
    end else if (sext_ln1198_3_fu_936_p1[25] == 1'b1) begin
        l_4_fu_940_p3 = 32'd25;
    end else if (sext_ln1198_3_fu_936_p1[26] == 1'b1) begin
        l_4_fu_940_p3 = 32'd26;
    end else if (sext_ln1198_3_fu_936_p1[27] == 1'b1) begin
        l_4_fu_940_p3 = 32'd27;
    end else if (sext_ln1198_3_fu_936_p1[28] == 1'b1) begin
        l_4_fu_940_p3 = 32'd28;
    end else if (sext_ln1198_3_fu_936_p1[29] == 1'b1) begin
        l_4_fu_940_p3 = 32'd29;
    end else if (sext_ln1198_3_fu_936_p1[30] == 1'b1) begin
        l_4_fu_940_p3 = 32'd30;
    end else if (sext_ln1198_3_fu_936_p1[31] == 1'b1) begin
        l_4_fu_940_p3 = 32'd31;
    end else begin
        l_4_fu_940_p3 = 32'd32;
    end
end


always @ (sext_ln1198_4_fu_1235_p1) begin
    if (sext_ln1198_4_fu_1235_p1[0] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd0;
    end else if (sext_ln1198_4_fu_1235_p1[1] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd1;
    end else if (sext_ln1198_4_fu_1235_p1[2] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd2;
    end else if (sext_ln1198_4_fu_1235_p1[3] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd3;
    end else if (sext_ln1198_4_fu_1235_p1[4] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd4;
    end else if (sext_ln1198_4_fu_1235_p1[5] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd5;
    end else if (sext_ln1198_4_fu_1235_p1[6] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd6;
    end else if (sext_ln1198_4_fu_1235_p1[7] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd7;
    end else if (sext_ln1198_4_fu_1235_p1[8] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd8;
    end else if (sext_ln1198_4_fu_1235_p1[9] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd9;
    end else if (sext_ln1198_4_fu_1235_p1[10] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd10;
    end else if (sext_ln1198_4_fu_1235_p1[11] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd11;
    end else if (sext_ln1198_4_fu_1235_p1[12] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd12;
    end else if (sext_ln1198_4_fu_1235_p1[13] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd13;
    end else if (sext_ln1198_4_fu_1235_p1[14] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd14;
    end else if (sext_ln1198_4_fu_1235_p1[15] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd15;
    end else if (sext_ln1198_4_fu_1235_p1[16] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd16;
    end else if (sext_ln1198_4_fu_1235_p1[17] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd17;
    end else if (sext_ln1198_4_fu_1235_p1[18] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd18;
    end else if (sext_ln1198_4_fu_1235_p1[19] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd19;
    end else if (sext_ln1198_4_fu_1235_p1[20] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd20;
    end else if (sext_ln1198_4_fu_1235_p1[21] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd21;
    end else if (sext_ln1198_4_fu_1235_p1[22] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd22;
    end else if (sext_ln1198_4_fu_1235_p1[23] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd23;
    end else if (sext_ln1198_4_fu_1235_p1[24] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd24;
    end else if (sext_ln1198_4_fu_1235_p1[25] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd25;
    end else if (sext_ln1198_4_fu_1235_p1[26] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd26;
    end else if (sext_ln1198_4_fu_1235_p1[27] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd27;
    end else if (sext_ln1198_4_fu_1235_p1[28] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd28;
    end else if (sext_ln1198_4_fu_1235_p1[29] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd29;
    end else if (sext_ln1198_4_fu_1235_p1[30] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd30;
    end else if (sext_ln1198_4_fu_1235_p1[31] == 1'b1) begin
        l_5_fu_1239_p3 = 32'd31;
    end else begin
        l_5_fu_1239_p3 = 32'd32;
    end
end


always @ (sext_ln1198_5_fu_1534_p1) begin
    if (sext_ln1198_5_fu_1534_p1[0] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd0;
    end else if (sext_ln1198_5_fu_1534_p1[1] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd1;
    end else if (sext_ln1198_5_fu_1534_p1[2] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd2;
    end else if (sext_ln1198_5_fu_1534_p1[3] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd3;
    end else if (sext_ln1198_5_fu_1534_p1[4] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd4;
    end else if (sext_ln1198_5_fu_1534_p1[5] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd5;
    end else if (sext_ln1198_5_fu_1534_p1[6] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd6;
    end else if (sext_ln1198_5_fu_1534_p1[7] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd7;
    end else if (sext_ln1198_5_fu_1534_p1[8] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd8;
    end else if (sext_ln1198_5_fu_1534_p1[9] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd9;
    end else if (sext_ln1198_5_fu_1534_p1[10] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd10;
    end else if (sext_ln1198_5_fu_1534_p1[11] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd11;
    end else if (sext_ln1198_5_fu_1534_p1[12] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd12;
    end else if (sext_ln1198_5_fu_1534_p1[13] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd13;
    end else if (sext_ln1198_5_fu_1534_p1[14] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd14;
    end else if (sext_ln1198_5_fu_1534_p1[15] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd15;
    end else if (sext_ln1198_5_fu_1534_p1[16] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd16;
    end else if (sext_ln1198_5_fu_1534_p1[17] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd17;
    end else if (sext_ln1198_5_fu_1534_p1[18] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd18;
    end else if (sext_ln1198_5_fu_1534_p1[19] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd19;
    end else if (sext_ln1198_5_fu_1534_p1[20] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd20;
    end else if (sext_ln1198_5_fu_1534_p1[21] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd21;
    end else if (sext_ln1198_5_fu_1534_p1[22] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd22;
    end else if (sext_ln1198_5_fu_1534_p1[23] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd23;
    end else if (sext_ln1198_5_fu_1534_p1[24] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd24;
    end else if (sext_ln1198_5_fu_1534_p1[25] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd25;
    end else if (sext_ln1198_5_fu_1534_p1[26] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd26;
    end else if (sext_ln1198_5_fu_1534_p1[27] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd27;
    end else if (sext_ln1198_5_fu_1534_p1[28] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd28;
    end else if (sext_ln1198_5_fu_1534_p1[29] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd29;
    end else if (sext_ln1198_5_fu_1534_p1[30] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd30;
    end else if (sext_ln1198_5_fu_1534_p1[31] == 1'b1) begin
        l_6_fu_1538_p3 = 32'd31;
    end else begin
        l_6_fu_1538_p3 = 32'd32;
    end
end


always @ (sext_ln1198_6_fu_1833_p1) begin
    if (sext_ln1198_6_fu_1833_p1[0] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd0;
    end else if (sext_ln1198_6_fu_1833_p1[1] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd1;
    end else if (sext_ln1198_6_fu_1833_p1[2] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd2;
    end else if (sext_ln1198_6_fu_1833_p1[3] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd3;
    end else if (sext_ln1198_6_fu_1833_p1[4] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd4;
    end else if (sext_ln1198_6_fu_1833_p1[5] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd5;
    end else if (sext_ln1198_6_fu_1833_p1[6] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd6;
    end else if (sext_ln1198_6_fu_1833_p1[7] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd7;
    end else if (sext_ln1198_6_fu_1833_p1[8] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd8;
    end else if (sext_ln1198_6_fu_1833_p1[9] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd9;
    end else if (sext_ln1198_6_fu_1833_p1[10] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd10;
    end else if (sext_ln1198_6_fu_1833_p1[11] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd11;
    end else if (sext_ln1198_6_fu_1833_p1[12] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd12;
    end else if (sext_ln1198_6_fu_1833_p1[13] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd13;
    end else if (sext_ln1198_6_fu_1833_p1[14] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd14;
    end else if (sext_ln1198_6_fu_1833_p1[15] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd15;
    end else if (sext_ln1198_6_fu_1833_p1[16] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd16;
    end else if (sext_ln1198_6_fu_1833_p1[17] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd17;
    end else if (sext_ln1198_6_fu_1833_p1[18] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd18;
    end else if (sext_ln1198_6_fu_1833_p1[19] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd19;
    end else if (sext_ln1198_6_fu_1833_p1[20] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd20;
    end else if (sext_ln1198_6_fu_1833_p1[21] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd21;
    end else if (sext_ln1198_6_fu_1833_p1[22] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd22;
    end else if (sext_ln1198_6_fu_1833_p1[23] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd23;
    end else if (sext_ln1198_6_fu_1833_p1[24] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd24;
    end else if (sext_ln1198_6_fu_1833_p1[25] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd25;
    end else if (sext_ln1198_6_fu_1833_p1[26] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd26;
    end else if (sext_ln1198_6_fu_1833_p1[27] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd27;
    end else if (sext_ln1198_6_fu_1833_p1[28] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd28;
    end else if (sext_ln1198_6_fu_1833_p1[29] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd29;
    end else if (sext_ln1198_6_fu_1833_p1[30] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd30;
    end else if (sext_ln1198_6_fu_1833_p1[31] == 1'b1) begin
        l_7_fu_1837_p3 = 32'd31;
    end else begin
        l_7_fu_1837_p3 = 32'd32;
    end
end


always @ (sext_ln1198_fu_338_p1) begin
    if (sext_ln1198_fu_338_p1[0] == 1'b1) begin
        l_fu_342_p3 = 32'd0;
    end else if (sext_ln1198_fu_338_p1[1] == 1'b1) begin
        l_fu_342_p3 = 32'd1;
    end else if (sext_ln1198_fu_338_p1[2] == 1'b1) begin
        l_fu_342_p3 = 32'd2;
    end else if (sext_ln1198_fu_338_p1[3] == 1'b1) begin
        l_fu_342_p3 = 32'd3;
    end else if (sext_ln1198_fu_338_p1[4] == 1'b1) begin
        l_fu_342_p3 = 32'd4;
    end else if (sext_ln1198_fu_338_p1[5] == 1'b1) begin
        l_fu_342_p3 = 32'd5;
    end else if (sext_ln1198_fu_338_p1[6] == 1'b1) begin
        l_fu_342_p3 = 32'd6;
    end else if (sext_ln1198_fu_338_p1[7] == 1'b1) begin
        l_fu_342_p3 = 32'd7;
    end else if (sext_ln1198_fu_338_p1[8] == 1'b1) begin
        l_fu_342_p3 = 32'd8;
    end else if (sext_ln1198_fu_338_p1[9] == 1'b1) begin
        l_fu_342_p3 = 32'd9;
    end else if (sext_ln1198_fu_338_p1[10] == 1'b1) begin
        l_fu_342_p3 = 32'd10;
    end else if (sext_ln1198_fu_338_p1[11] == 1'b1) begin
        l_fu_342_p3 = 32'd11;
    end else if (sext_ln1198_fu_338_p1[12] == 1'b1) begin
        l_fu_342_p3 = 32'd12;
    end else if (sext_ln1198_fu_338_p1[13] == 1'b1) begin
        l_fu_342_p3 = 32'd13;
    end else if (sext_ln1198_fu_338_p1[14] == 1'b1) begin
        l_fu_342_p3 = 32'd14;
    end else if (sext_ln1198_fu_338_p1[15] == 1'b1) begin
        l_fu_342_p3 = 32'd15;
    end else if (sext_ln1198_fu_338_p1[16] == 1'b1) begin
        l_fu_342_p3 = 32'd16;
    end else if (sext_ln1198_fu_338_p1[17] == 1'b1) begin
        l_fu_342_p3 = 32'd17;
    end else if (sext_ln1198_fu_338_p1[18] == 1'b1) begin
        l_fu_342_p3 = 32'd18;
    end else if (sext_ln1198_fu_338_p1[19] == 1'b1) begin
        l_fu_342_p3 = 32'd19;
    end else if (sext_ln1198_fu_338_p1[20] == 1'b1) begin
        l_fu_342_p3 = 32'd20;
    end else if (sext_ln1198_fu_338_p1[21] == 1'b1) begin
        l_fu_342_p3 = 32'd21;
    end else if (sext_ln1198_fu_338_p1[22] == 1'b1) begin
        l_fu_342_p3 = 32'd22;
    end else if (sext_ln1198_fu_338_p1[23] == 1'b1) begin
        l_fu_342_p3 = 32'd23;
    end else if (sext_ln1198_fu_338_p1[24] == 1'b1) begin
        l_fu_342_p3 = 32'd24;
    end else if (sext_ln1198_fu_338_p1[25] == 1'b1) begin
        l_fu_342_p3 = 32'd25;
    end else if (sext_ln1198_fu_338_p1[26] == 1'b1) begin
        l_fu_342_p3 = 32'd26;
    end else if (sext_ln1198_fu_338_p1[27] == 1'b1) begin
        l_fu_342_p3 = 32'd27;
    end else if (sext_ln1198_fu_338_p1[28] == 1'b1) begin
        l_fu_342_p3 = 32'd28;
    end else if (sext_ln1198_fu_338_p1[29] == 1'b1) begin
        l_fu_342_p3 = 32'd29;
    end else if (sext_ln1198_fu_338_p1[30] == 1'b1) begin
        l_fu_342_p3 = 32'd30;
    end else if (sext_ln1198_fu_338_p1[31] == 1'b1) begin
        l_fu_342_p3 = 32'd31;
    end else begin
        l_fu_342_p3 = 32'd32;
    end
end

assign lsb_index_3_fu_659_p2 = ($signed(sub_ln1099_3_fu_649_p2) + $signed(32'd4294967272));

assign lsb_index_4_fu_958_p2 = ($signed(sub_ln1099_4_fu_948_p2) + $signed(32'd4294967272));

assign lsb_index_5_fu_1257_p2 = ($signed(sub_ln1099_5_fu_1247_p2) + $signed(32'd4294967272));

assign lsb_index_6_fu_1556_p2 = ($signed(sub_ln1099_6_fu_1546_p2) + $signed(32'd4294967272));

assign lsb_index_7_fu_1855_p2 = ($signed(sub_ln1099_7_fu_1845_p2) + $signed(32'd4294967272));

assign lsb_index_fu_360_p2 = ($signed(sub_ln1099_fu_350_p2) + $signed(32'd4294967272));

assign lshr_ln1102_3_fu_695_p2 = 24'd16777215 >> zext_ln1102_3_fu_691_p1;

assign lshr_ln1102_4_fu_994_p2 = 24'd16777215 >> zext_ln1102_4_fu_990_p1;

assign lshr_ln1102_5_fu_1293_p2 = 24'd16777215 >> zext_ln1102_5_fu_1289_p1;

assign lshr_ln1102_6_fu_1592_p2 = 24'd16777215 >> zext_ln1102_6_fu_1588_p1;

assign lshr_ln1102_7_fu_1891_p2 = 24'd16777215 >> zext_ln1102_7_fu_1887_p1;

assign lshr_ln1102_fu_396_p2 = 24'd16777215 >> zext_ln1102_fu_392_p1;

assign lshr_ln1113_2_fu_787_p2 = zext_ln1112_2_fu_767_p1 >> zext_ln1113_2_fu_783_p1;

assign lshr_ln1113_3_fu_1086_p2 = zext_ln1112_3_fu_1066_p1 >> zext_ln1113_3_fu_1082_p1;

assign lshr_ln1113_4_fu_1385_p2 = zext_ln1112_4_fu_1365_p1 >> zext_ln1113_4_fu_1381_p1;

assign lshr_ln1113_5_fu_1684_p2 = zext_ln1112_5_fu_1664_p1 >> zext_ln1113_5_fu_1680_p1;

assign lshr_ln1113_6_fu_1983_p2 = zext_ln1112_6_fu_1963_p1 >> zext_ln1113_6_fu_1979_p1;

assign lshr_ln1113_fu_488_p2 = zext_ln1112_fu_468_p1 >> zext_ln1113_fu_484_p1;

assign m_16_fu_510_p3 = ((icmp_ln1113_fu_472_p2[0:0] == 1'b1) ? lshr_ln1113_fu_488_p2 : shl_ln1114_fu_504_p2);

assign m_17_fu_522_p2 = (m_16_fu_510_p3 + zext_ln1116_fu_518_p1);

assign m_19_fu_809_p3 = ((icmp_ln1113_2_fu_771_p2[0:0] == 1'b1) ? lshr_ln1113_2_fu_787_p2 : shl_ln1114_2_fu_803_p2);

assign m_20_fu_821_p2 = (m_19_fu_809_p3 + zext_ln1116_3_fu_817_p1);

assign m_24_fu_1108_p3 = ((icmp_ln1113_3_fu_1070_p2[0:0] == 1'b1) ? lshr_ln1113_3_fu_1086_p2 : shl_ln1114_3_fu_1102_p2);

assign m_25_fu_1120_p2 = (m_24_fu_1108_p3 + zext_ln1116_4_fu_1116_p1);

assign m_28_fu_1407_p3 = ((icmp_ln1113_4_fu_1369_p2[0:0] == 1'b1) ? lshr_ln1113_4_fu_1385_p2 : shl_ln1114_4_fu_1401_p2);

assign m_29_fu_1419_p2 = (m_28_fu_1407_p3 + zext_ln1116_5_fu_1415_p1);

assign m_32_fu_1706_p3 = ((icmp_ln1113_5_fu_1668_p2[0:0] == 1'b1) ? lshr_ln1113_5_fu_1684_p2 : shl_ln1114_5_fu_1700_p2);

assign m_33_fu_1718_p2 = (m_32_fu_1706_p3 + zext_ln1116_6_fu_1714_p1);

assign m_36_fu_2005_p3 = ((icmp_ln1113_6_fu_1967_p2[0:0] == 1'b1) ? lshr_ln1113_6_fu_1983_p2 : shl_ln1114_6_fu_1999_p2);

assign m_37_fu_2017_p2 = (m_36_fu_2005_p3 + zext_ln1116_7_fu_2013_p1);

assign m_39_fu_528_p4 = {{m_17_fu_522_p2[63:1]}};

assign m_40_fu_1126_p4 = {{m_25_fu_1120_p2[63:1]}};

assign m_41_fu_1425_p4 = {{m_29_fu_1419_p2[63:1]}};

assign m_42_fu_1724_p4 = {{m_33_fu_1718_p2[63:1]}};

assign m_43_fu_2023_p4 = {{m_37_fu_2017_p2[63:1]}};

assign m_fu_827_p4 = {{m_20_fu_821_p2[63:1]}};

assign mantissa_2_fu_2460_p4 = {{{{1'd1}, {p_Result_131_fu_2456_p1}}}, {1'd0}};

assign mantissa_fu_2309_p4 = {{{{1'd1}, {p_Result_129_fu_2305_p1}}}, {1'd0}};

assign or_ln1104_10_fu_1351_p2 = (and_ln1104_5_fu_1345_p2 | a_5_fu_1311_p2);

assign or_ln1104_11_fu_1650_p2 = (and_ln1104_6_fu_1644_p2 | a_6_fu_1610_p2);

assign or_ln1104_12_fu_1949_p2 = (and_ln1104_7_fu_1943_p2 | a_7_fu_1909_p2);

assign or_ln1104_3_fu_759_p3 = {{1'd0}, {or_ln1104_fu_753_p2}};

assign or_ln1104_4_fu_1058_p3 = {{1'd0}, {or_ln1104_9_fu_1052_p2}};

assign or_ln1104_5_fu_1357_p3 = {{1'd0}, {or_ln1104_10_fu_1351_p2}};

assign or_ln1104_6_fu_1656_p3 = {{1'd0}, {or_ln1104_11_fu_1650_p2}};

assign or_ln1104_7_fu_1955_p3 = {{1'd0}, {or_ln1104_12_fu_1949_p2}};

assign or_ln1104_8_fu_454_p2 = (and_ln1104_fu_448_p2 | a_fu_414_p2);

assign or_ln1104_9_fu_1052_p2 = (and_ln1104_4_fu_1046_p2 | a_4_fu_1012_p2);

assign or_ln1104_fu_753_p2 = (and_ln1104_3_fu_747_p2 | a_3_fu_713_p2);

assign or_ln200_1_fu_2181_p2 = (icmp_ln200_4_fu_2175_p2 | icmp_ln200_3_fu_2169_p2);

assign or_ln200_fu_2133_p2 = (icmp_ln200_fu_2121_p2 | icmp_ln200_2_fu_2127_p2);

assign or_ln224_1_fu_2267_p2 = (icmp_ln224_4_reg_3458_pp0_iter19_reg | icmp_ln224_3_reg_3453_pp0_iter19_reg);

assign or_ln224_fu_2258_p2 = (icmp_ln224_reg_3443_pp0_iter19_reg | icmp_ln224_2_reg_3448_pp0_iter19_reg);

assign or_ln_fu_460_p3 = {{1'd0}, {or_ln1104_8_fu_454_p2}};

assign p_Result_100_fu_1897_p2 = (tmp_V_27_fu_1810_p3 & lshr_ln1102_7_fu_1891_p2);

assign p_Result_101_fu_1935_p3 = tmp_V_27_fu_1810_p3[add_ln1104_6_fu_1929_p2];

assign p_Result_102_fu_2037_p3 = m_37_fu_2017_p2[32'd25];

assign p_Result_111_fu_330_p3 = {{1'd1}, {p_Result_s_fu_320_p4}};

assign p_Result_112_fu_581_p5 = {{zext_ln1117_fu_538_p1[63:32]}, {tmp_s_fu_574_p3}, {zext_ln1117_fu_538_p1[22:0]}};

assign p_Result_114_fu_629_p3 = {{1'd1}, {p_Result_70_fu_619_p4}};

assign p_Result_115_fu_880_p5 = {{zext_ln1117_2_fu_837_p1[63:32]}, {tmp_5_fu_873_p3}, {zext_ln1117_2_fu_837_p1[22:0]}};

assign p_Result_117_fu_928_p3 = {{1'd1}, {p_Result_77_fu_918_p4}};

assign p_Result_118_fu_1179_p5 = {{zext_ln1117_3_fu_1136_p1[63:32]}, {tmp_6_fu_1172_p3}, {zext_ln1117_3_fu_1136_p1[22:0]}};

assign p_Result_120_fu_1227_p3 = {{1'd1}, {p_Result_84_fu_1217_p4}};

assign p_Result_121_fu_1478_p5 = {{zext_ln1117_4_fu_1435_p1[63:32]}, {tmp_7_fu_1471_p3}, {zext_ln1117_4_fu_1435_p1[22:0]}};

assign p_Result_123_fu_1526_p3 = {{1'd1}, {p_Result_91_fu_1516_p4}};

assign p_Result_124_fu_1777_p5 = {{zext_ln1117_5_fu_1734_p1[63:32]}, {tmp_8_fu_1770_p3}, {zext_ln1117_5_fu_1734_p1[22:0]}};

assign p_Result_126_fu_1825_p3 = {{1'd1}, {p_Result_98_fu_1815_p4}};

assign p_Result_127_fu_2076_p5 = {{zext_ln1117_6_fu_2033_p1[63:32]}, {tmp_9_fu_2069_p3}, {zext_ln1117_6_fu_2033_p1[22:0]}};

assign p_Result_128_fu_2287_p3 = data_V_fu_2279_p3[32'd31];

assign p_Result_129_fu_2305_p1 = data_V_fu_2279_p3[22:0];

assign p_Result_130_fu_2438_p3 = data_V_2_fu_2430_p3[32'd31];

assign p_Result_131_fu_2456_p1 = data_V_2_fu_2430_p3[22:0];

assign p_Result_65_fu_402_p2 = (tmp_V_22_fu_315_p3 & lshr_ln1102_fu_396_p2);

assign p_Result_66_fu_440_p3 = tmp_V_22_fu_315_p3[add_ln1104_fu_434_p2];

assign p_Result_67_fu_542_p3 = m_17_fu_522_p2[32'd25];

integer ap_tvar_int_0;

always @ (tmp_V_23_fu_614_p3) begin
    for (ap_tvar_int_0 = 24 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 23 - 0) begin
            p_Result_70_fu_619_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_70_fu_619_p4[ap_tvar_int_0] = tmp_V_23_fu_614_p3[23 - ap_tvar_int_0];
        end
    end
end

assign p_Result_72_fu_701_p2 = (tmp_V_23_fu_614_p3 & lshr_ln1102_3_fu_695_p2);

assign p_Result_73_fu_739_p3 = tmp_V_23_fu_614_p3[add_ln1104_2_fu_733_p2];

assign p_Result_74_fu_841_p3 = m_20_fu_821_p2[32'd25];

integer ap_tvar_int_1;

always @ (tmp_V_24_fu_913_p3) begin
    for (ap_tvar_int_1 = 24 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 23 - 0) begin
            p_Result_77_fu_918_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_77_fu_918_p4[ap_tvar_int_1] = tmp_V_24_fu_913_p3[23 - ap_tvar_int_1];
        end
    end
end

assign p_Result_79_fu_1000_p2 = (tmp_V_24_fu_913_p3 & lshr_ln1102_4_fu_994_p2);

assign p_Result_80_fu_1038_p3 = tmp_V_24_fu_913_p3[add_ln1104_3_fu_1032_p2];

assign p_Result_81_fu_1140_p3 = m_25_fu_1120_p2[32'd25];

integer ap_tvar_int_2;

always @ (tmp_V_25_fu_1212_p3) begin
    for (ap_tvar_int_2 = 24 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 23 - 0) begin
            p_Result_84_fu_1217_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            p_Result_84_fu_1217_p4[ap_tvar_int_2] = tmp_V_25_fu_1212_p3[23 - ap_tvar_int_2];
        end
    end
end

assign p_Result_86_fu_1299_p2 = (tmp_V_25_fu_1212_p3 & lshr_ln1102_5_fu_1293_p2);

assign p_Result_87_fu_1337_p3 = tmp_V_25_fu_1212_p3[add_ln1104_4_fu_1331_p2];

assign p_Result_88_fu_1439_p3 = m_29_fu_1419_p2[32'd25];

integer ap_tvar_int_3;

always @ (tmp_V_26_fu_1511_p3) begin
    for (ap_tvar_int_3 = 24 - 1; ap_tvar_int_3 >= 0; ap_tvar_int_3 = ap_tvar_int_3 - 1) begin
        if (ap_tvar_int_3 > 23 - 0) begin
            p_Result_91_fu_1516_p4[ap_tvar_int_3] = 1'b0;
        end else begin
            p_Result_91_fu_1516_p4[ap_tvar_int_3] = tmp_V_26_fu_1511_p3[23 - ap_tvar_int_3];
        end
    end
end

assign p_Result_93_fu_1598_p2 = (tmp_V_26_fu_1511_p3 & lshr_ln1102_6_fu_1592_p2);

assign p_Result_94_fu_1636_p3 = tmp_V_26_fu_1511_p3[add_ln1104_5_fu_1630_p2];

assign p_Result_95_fu_1738_p3 = m_33_fu_1718_p2[32'd25];

integer ap_tvar_int_4;

always @ (tmp_V_27_fu_1810_p3) begin
    for (ap_tvar_int_4 = 24 - 1; ap_tvar_int_4 >= 0; ap_tvar_int_4 = ap_tvar_int_4 - 1) begin
        if (ap_tvar_int_4 > 23 - 0) begin
            p_Result_98_fu_1815_p4[ap_tvar_int_4] = 1'b0;
        end else begin
            p_Result_98_fu_1815_p4[ap_tvar_int_4] = tmp_V_27_fu_1810_p3[23 - ap_tvar_int_4];
        end
    end
end

integer ap_tvar_int_5;

always @ (tmp_V_22_fu_315_p3) begin
    for (ap_tvar_int_5 = 24 - 1; ap_tvar_int_5 >= 0; ap_tvar_int_5 = ap_tvar_int_5 - 1) begin
        if (ap_tvar_int_5 > 23 - 0) begin
            p_Result_s_fu_320_p4[ap_tvar_int_5] = 1'b0;
        end else begin
            p_Result_s_fu_320_p4[ap_tvar_int_5] = tmp_V_22_fu_315_p3[23 - ap_tvar_int_5];
        end
    end
end

assign r_V_48_fu_2373_p2 = zext_ln15_fu_2319_p1 << zext_ln1488_fu_2363_p1;

assign r_V_49_fu_2518_p2 = zext_ln15_2_fu_2470_p1 >> zext_ln1488_2_fu_2514_p1;

assign r_V_50_fu_2524_p2 = zext_ln15_2_fu_2470_p1 << zext_ln1488_2_fu_2514_p1;

assign r_V_fu_2367_p2 = zext_ln15_fu_2319_p1 >> zext_ln1488_fu_2363_p1;

assign result_V_11_fu_2409_p2 = (8'd0 - val_fu_2401_p3);

assign result_V_14_fu_2560_p2 = (8'd0 - val_2_fu_2552_p3);

assign result_V_15_fu_2566_p3 = ((p_Result_130_fu_2438_p3[0:0] == 1'b1) ? result_V_14_fu_2560_p2 : val_2_fu_2552_p3);

assign result_V_fu_2415_p3 = ((p_Result_128_fu_2287_p3[0:0] == 1'b1) ? result_V_11_fu_2409_p2 : val_fu_2401_p3);

assign rx_fu_2423_p1 = result_V_fu_2415_p3[0:0];

assign ry_fu_2574_p1 = result_V_15_fu_2566_p3[0:0];

assign select_ln1098_3_fu_849_p3 = ((p_Result_74_fu_841_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln1098_4_fu_1148_p3 = ((p_Result_81_fu_1140_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln1098_5_fu_1447_p3 = ((p_Result_88_fu_1439_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln1098_6_fu_1746_p3 = ((p_Result_95_fu_1738_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln1098_7_fu_2045_p3 = ((p_Result_102_fu_2037_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln1098_fu_550_p3 = ((p_Result_67_fu_542_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln224_2_fu_2193_p3 = ((and_ln200_1_fu_2187_p2[0:0] == 1'b1) ? div9_reg_3422_pp0_iter15_reg : 32'd1065353216);

assign select_ln224_fu_2145_p3 = ((and_ln200_fu_2139_p2[0:0] == 1'b1) ? div_reg_3415_pp0_iter15_reg : 32'd1065353216);

assign select_ln93_10_fu_3082_p3 = ((tmp_83_fu_3012_p3[0:0] == 1'b1) ? select_ln93_8_fu_2988_p3 : t_14_fu_3074_p3);

assign select_ln93_11_fu_3090_p3 = ((tmp_83_fu_3012_p3[0:0] == 1'b1) ? select_ln93_9_fu_2996_p3 : select_ln99_10_fu_3066_p3);

assign select_ln93_12_fu_3192_p3 = ((tmp_87_fu_3106_p3[0:0] == 1'b1) ? tmp_92_fu_3184_p3 : select_ln99_12_fu_3176_p3);

assign select_ln93_13_fu_3216_p3 = ((tmp_87_fu_3106_p3[0:0] == 1'b1) ? tmp_91_fu_3168_p3 : select_ln99_13_fu_3208_p3);

assign select_ln93_1_fu_2614_p3 = ((ry_fu_2574_p1[0:0] == 1'b1) ? result_V_fu_2415_p3 : select_ln99_fu_2590_p3);

assign select_ln93_2_fu_2710_p3 = ((tmp_67_reg_3513[0:0] == 1'b1) ? select_ln93_reg_3493 : t_10_fu_2704_p3);

assign select_ln93_3_fu_2716_p3 = ((tmp_67_reg_3513[0:0] == 1'b1) ? select_ln93_1_reg_3500 : select_ln99_2_fu_2698_p3);

assign select_ln93_4_fu_2800_p3 = ((tmp_71_fu_2730_p3[0:0] == 1'b1) ? select_ln93_2_fu_2710_p3 : t_11_fu_2792_p3);

assign select_ln93_5_fu_2808_p3 = ((tmp_71_fu_2730_p3[0:0] == 1'b1) ? select_ln93_3_fu_2716_p3 : select_ln99_4_fu_2784_p3);

assign select_ln93_6_fu_2894_p3 = ((tmp_75_fu_2824_p3[0:0] == 1'b1) ? select_ln93_4_fu_2800_p3 : t_12_fu_2886_p3);

assign select_ln93_7_fu_2902_p3 = ((tmp_75_fu_2824_p3[0:0] == 1'b1) ? select_ln93_5_fu_2808_p3 : select_ln99_6_fu_2878_p3);

assign select_ln93_8_fu_2988_p3 = ((tmp_79_fu_2918_p3[0:0] == 1'b1) ? select_ln93_6_fu_2894_p3 : t_13_fu_2980_p3);

assign select_ln93_9_fu_2996_p3 = ((tmp_79_fu_2918_p3[0:0] == 1'b1) ? select_ln93_7_fu_2902_p3 : select_ln99_8_fu_2972_p3);

assign select_ln93_fu_2606_p3 = ((ry_fu_2574_p1[0:0] == 1'b1) ? result_V_15_fu_2566_p3 : t_9_fu_2598_p3);

assign select_ln95_1_fu_2658_p3 = ((tmp_68_fu_2638_p3[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln95_2_fu_2758_p3 = ((tmp_72_fu_2738_p3[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln95_3_fu_2852_p3 = ((tmp_76_fu_2832_p3[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln95_4_fu_2946_p3 = ((tmp_80_fu_2926_p3[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln95_5_fu_3040_p3 = ((tmp_84_fu_3020_p3[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln95_6_fu_3134_p3 = ((tmp_88_fu_3114_p3[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln95_7_fu_3228_p3 = ((select_ln93_12_fu_3192_p3[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln95_fu_2675_p3 = ((rx_reg_3483[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln99_10_fu_3066_p3 = ((tmp_82_fu_3004_p3[0:0] == 1'b1) ? sub_ln101_5_fu_3060_p2 : select_ln93_8_fu_2988_p3);

assign select_ln99_12_fu_3176_p3 = ((tmp_86_fu_3098_p3[0:0] == 1'b1) ? tmp_90_fu_3160_p3 : tmp_91_fu_3168_p3);

assign select_ln99_13_fu_3208_p3 = ((tmp_86_fu_3098_p3[0:0] == 1'b1) ? tmp_93_fu_3200_p3 : tmp_92_fu_3184_p3);

assign select_ln99_2_fu_2698_p3 = ((tmp_66_reg_3507[0:0] == 1'b1) ? sub_ln101_1_fu_2693_p2 : select_ln93_reg_3493);

assign select_ln99_4_fu_2784_p3 = ((tmp_70_fu_2722_p3[0:0] == 1'b1) ? sub_ln101_2_fu_2778_p2 : select_ln93_2_fu_2710_p3);

assign select_ln99_6_fu_2878_p3 = ((tmp_74_fu_2816_p3[0:0] == 1'b1) ? sub_ln101_3_fu_2872_p2 : select_ln93_4_fu_2800_p3);

assign select_ln99_8_fu_2972_p3 = ((tmp_78_fu_2910_p3[0:0] == 1'b1) ? sub_ln101_4_fu_2966_p2 : select_ln93_6_fu_2894_p3);

assign select_ln99_fu_2590_p3 = ((rx_fu_2423_p1[0:0] == 1'b1) ? sub_ln101_fu_2584_p2 : result_V_15_fu_2566_p3);

assign sext_ln1198_2_fu_637_p1 = $signed(p_Result_114_fu_629_p3);

assign sext_ln1198_3_fu_936_p1 = $signed(p_Result_117_fu_928_p3);

assign sext_ln1198_4_fu_1235_p1 = $signed(p_Result_120_fu_1227_p3);

assign sext_ln1198_5_fu_1534_p1 = $signed(p_Result_123_fu_1526_p3);

assign sext_ln1198_6_fu_1833_p1 = $signed(p_Result_126_fu_1825_p3);

assign sext_ln1198_fu_338_p1 = $signed(p_Result_111_fu_330_p3);

assign sext_ln1488_2_fu_2510_p1 = $signed(ush_2_fu_2502_p3);

assign sext_ln1488_fu_2359_p1 = $signed(ush_fu_2351_p3);

assign sext_ln1512_2_fu_2498_p1 = $signed(sub_ln1512_2_fu_2492_p2);

assign sext_ln1512_fu_2347_p1 = $signed(sub_ln1512_fu_2341_p2);

assign shl_ln1114_2_fu_803_p2 = zext_ln1112_2_fu_767_p1 << zext_ln1114_2_fu_799_p1;

assign shl_ln1114_3_fu_1102_p2 = zext_ln1112_3_fu_1066_p1 << zext_ln1114_3_fu_1098_p1;

assign shl_ln1114_4_fu_1401_p2 = zext_ln1112_4_fu_1365_p1 << zext_ln1114_4_fu_1397_p1;

assign shl_ln1114_5_fu_1700_p2 = zext_ln1112_5_fu_1664_p1 << zext_ln1114_5_fu_1696_p1;

assign shl_ln1114_6_fu_1999_p2 = zext_ln1112_6_fu_1963_p1 << zext_ln1114_6_fu_1995_p1;

assign shl_ln1114_fu_504_p2 = zext_ln1112_fu_468_p1 << zext_ln1114_fu_500_p1;

assign sub_ln100_1_fu_2688_p2 = (8'd1 - select_ln93_1_reg_3500);

assign sub_ln100_2_fu_2772_p2 = (8'd3 - select_ln93_3_fu_2716_p3);

assign sub_ln100_3_fu_2866_p2 = (8'd7 - select_ln93_5_fu_2808_p3);

assign sub_ln100_4_fu_2960_p2 = (8'd15 - select_ln93_7_fu_2902_p3);

assign sub_ln100_5_fu_3054_p2 = (8'd31 - select_ln93_9_fu_2996_p3);

assign sub_ln100_6_fu_3148_p2 = (8'd63 - select_ln93_11_fu_3090_p3);

assign sub_ln100_fu_2578_p2 = (8'd0 - result_V_fu_2415_p3);

assign sub_ln101_1_fu_2693_p2 = (8'd1 - select_ln93_reg_3493);

assign sub_ln101_2_fu_2778_p2 = (8'd3 - select_ln93_2_fu_2710_p3);

assign sub_ln101_3_fu_2872_p2 = (8'd7 - select_ln93_4_fu_2800_p3);

assign sub_ln101_4_fu_2966_p2 = (8'd15 - select_ln93_6_fu_2894_p3);

assign sub_ln101_5_fu_3060_p2 = (8'd31 - select_ln93_8_fu_2988_p3);

assign sub_ln101_6_fu_3154_p2 = (8'd63 - select_ln93_10_fu_3082_p3);

assign sub_ln101_fu_2584_p2 = (8'd0 - result_V_15_fu_2566_p3);

assign sub_ln1099_3_fu_649_p2 = (32'd24 - l_3_fu_641_p3);

assign sub_ln1099_4_fu_948_p2 = (32'd24 - l_4_fu_940_p3);

assign sub_ln1099_5_fu_1247_p2 = (32'd24 - l_5_fu_1239_p3);

assign sub_ln1099_6_fu_1546_p2 = (32'd24 - l_6_fu_1538_p3);

assign sub_ln1099_7_fu_1845_p2 = (32'd24 - l_7_fu_1837_p3);

assign sub_ln1099_fu_350_p2 = (32'd24 - l_fu_342_p3);

assign sub_ln1102_3_fu_685_p2 = ($signed(5'd17) - $signed(trunc_ln1102_3_fu_681_p1));

assign sub_ln1102_4_fu_984_p2 = ($signed(5'd17) - $signed(trunc_ln1102_4_fu_980_p1));

assign sub_ln1102_5_fu_1283_p2 = ($signed(5'd17) - $signed(trunc_ln1102_5_fu_1279_p1));

assign sub_ln1102_6_fu_1582_p2 = ($signed(5'd17) - $signed(trunc_ln1102_6_fu_1578_p1));

assign sub_ln1102_7_fu_1881_p2 = ($signed(5'd17) - $signed(trunc_ln1102_7_fu_1877_p1));

assign sub_ln1102_fu_386_p2 = ($signed(5'd17) - $signed(trunc_ln1102_fu_382_p1));

assign sub_ln1114_1_fu_793_p2 = (32'd25 - sub_ln1099_3_fu_649_p2);

assign sub_ln1114_2_fu_1092_p2 = (32'd25 - sub_ln1099_4_fu_948_p2);

assign sub_ln1114_3_fu_1391_p2 = (32'd25 - sub_ln1099_5_fu_1247_p2);

assign sub_ln1114_4_fu_1690_p2 = (32'd25 - sub_ln1099_6_fu_1546_p2);

assign sub_ln1114_5_fu_1989_p2 = (32'd25 - sub_ln1099_7_fu_1845_p2);

assign sub_ln1114_fu_494_p2 = (32'd25 - sub_ln1099_fu_350_p2);

assign sub_ln1119_3_fu_861_p2 = (8'd4 - trunc_ln1098_3_fu_857_p1);

assign sub_ln1119_4_fu_1160_p2 = (8'd4 - trunc_ln1098_4_fu_1156_p1);

assign sub_ln1119_5_fu_1459_p2 = (8'd4 - trunc_ln1098_5_fu_1455_p1);

assign sub_ln1119_6_fu_1758_p2 = (8'd4 - trunc_ln1098_6_fu_1754_p1);

assign sub_ln1119_7_fu_2057_p2 = (8'd4 - trunc_ln1098_7_fu_2053_p1);

assign sub_ln1119_fu_562_p2 = (8'd4 - trunc_ln1098_fu_558_p1);

assign sub_ln1512_2_fu_2492_p2 = (8'd127 - xs_exp_V_2_fu_2446_p4);

assign sub_ln1512_fu_2341_p2 = (8'd127 - xs_exp_V_fu_2295_p4);

assign t_10_fu_2704_p3 = ((tmp_66_reg_3507[0:0] == 1'b1) ? sub_ln100_1_fu_2688_p2 : select_ln93_1_reg_3500);

assign t_11_fu_2792_p3 = ((tmp_70_fu_2722_p3[0:0] == 1'b1) ? sub_ln100_2_fu_2772_p2 : select_ln93_3_fu_2716_p3);

assign t_12_fu_2886_p3 = ((tmp_74_fu_2816_p3[0:0] == 1'b1) ? sub_ln100_3_fu_2866_p2 : select_ln93_5_fu_2808_p3);

assign t_13_fu_2980_p3 = ((tmp_78_fu_2910_p3[0:0] == 1'b1) ? sub_ln100_4_fu_2960_p2 : select_ln93_7_fu_2902_p3);

assign t_14_fu_3074_p3 = ((tmp_82_fu_3004_p3[0:0] == 1'b1) ? sub_ln100_5_fu_3054_p2 : select_ln93_9_fu_2996_p3);

assign t_9_fu_2598_p3 = ((rx_fu_2423_p1[0:0] == 1'b1) ? sub_ln100_fu_2578_p2 : result_V_fu_2415_p3);

assign tmp_11_fu_2232_p4 = {{bitcast_ln224_1_fu_2229_p1[30:23]}};

assign tmp_14_fu_2391_p4 = {{r_V_48_fu_2373_p2[31:24]}};

assign tmp_15_fu_2542_p4 = {{r_V_50_fu_2524_p2[31:24]}};

assign tmp_1_fu_2203_p4 = {{bitcast_ln224_fu_2200_p1[30:23]}};

assign tmp_35_fu_366_p4 = {{lsb_index_fu_360_p2[31:1]}};

assign tmp_36_fu_420_p3 = lsb_index_fu_360_p2[32'd31];

assign tmp_39_fu_665_p4 = {{lsb_index_3_fu_659_p2[31:1]}};

assign tmp_3_fu_2155_p4 = {{bitcast_ln200_1_fu_2152_p1[30:23]}};

assign tmp_40_fu_719_p3 = lsb_index_3_fu_659_p2[32'd31];

assign tmp_43_fu_964_p4 = {{lsb_index_4_fu_958_p2[31:1]}};

assign tmp_44_fu_1018_p3 = lsb_index_4_fu_958_p2[32'd31];

assign tmp_47_fu_1263_p4 = {{lsb_index_5_fu_1257_p2[31:1]}};

assign tmp_48_fu_1317_p3 = lsb_index_5_fu_1257_p2[32'd31];

assign tmp_51_fu_1562_p4 = {{lsb_index_6_fu_1556_p2[31:1]}};

assign tmp_52_fu_1616_p3 = lsb_index_6_fu_1556_p2[32'd31];

assign tmp_55_fu_1861_p4 = {{lsb_index_7_fu_1855_p2[31:1]}};

assign tmp_56_fu_1915_p3 = lsb_index_7_fu_1855_p2[32'd31];

assign tmp_5_fu_873_p3 = {{p_Result_113_reg_3308}, {add_ln1124_3_fu_867_p2}};

assign tmp_61_fu_2379_p3 = r_V_fu_2367_p2[32'd24];

assign tmp_65_fu_2530_p3 = r_V_49_fu_2518_p2[32'd24];

assign tmp_68_fu_2638_p3 = select_ln93_1_fu_2614_p3[32'd1];

assign tmp_69_fu_2646_p3 = select_ln93_fu_2606_p3[32'd1];

assign tmp_6_fu_1172_p3 = {{p_Result_116_reg_3319}, {add_ln1124_4_fu_1166_p2}};

assign tmp_70_fu_2722_p3 = select_ln93_3_fu_2716_p3[32'd2];

assign tmp_71_fu_2730_p3 = select_ln93_2_fu_2710_p3[32'd2];

assign tmp_72_fu_2738_p3 = select_ln93_3_fu_2716_p3[32'd2];

assign tmp_73_fu_2746_p3 = select_ln93_2_fu_2710_p3[32'd2];

assign tmp_74_fu_2816_p3 = select_ln93_5_fu_2808_p3[32'd3];

assign tmp_75_fu_2824_p3 = select_ln93_4_fu_2800_p3[32'd3];

assign tmp_76_fu_2832_p3 = select_ln93_5_fu_2808_p3[32'd3];

assign tmp_77_fu_2840_p3 = select_ln93_4_fu_2800_p3[32'd3];

assign tmp_78_fu_2910_p3 = select_ln93_7_fu_2902_p3[32'd4];

assign tmp_79_fu_2918_p3 = select_ln93_6_fu_2894_p3[32'd4];

assign tmp_7_fu_1471_p3 = {{p_Result_119_reg_3330}, {add_ln1124_5_fu_1465_p2}};

assign tmp_80_fu_2926_p3 = select_ln93_7_fu_2902_p3[32'd4];

assign tmp_81_fu_2934_p3 = select_ln93_6_fu_2894_p3[32'd4];

assign tmp_82_fu_3004_p3 = select_ln93_9_fu_2996_p3[32'd5];

assign tmp_83_fu_3012_p3 = select_ln93_8_fu_2988_p3[32'd5];

assign tmp_84_fu_3020_p3 = select_ln93_9_fu_2996_p3[32'd5];

assign tmp_85_fu_3028_p3 = select_ln93_8_fu_2988_p3[32'd5];

assign tmp_86_fu_3098_p3 = select_ln93_11_fu_3090_p3[32'd6];

assign tmp_87_fu_3106_p3 = select_ln93_10_fu_3082_p3[32'd6];

assign tmp_88_fu_3114_p3 = select_ln93_11_fu_3090_p3[32'd6];

assign tmp_89_fu_3122_p3 = select_ln93_10_fu_3082_p3[32'd6];

assign tmp_8_fu_1770_p3 = {{p_Result_122_reg_3341}, {add_ln1124_6_fu_1764_p2}};

assign tmp_90_fu_3160_p3 = sub_ln101_6_fu_3154_p2[32'd7];

assign tmp_91_fu_3168_p3 = select_ln93_10_fu_3082_p3[32'd7];

assign tmp_92_fu_3184_p3 = select_ln93_11_fu_3090_p3[32'd7];

assign tmp_93_fu_3200_p3 = sub_ln100_6_fu_3148_p2[32'd7];

assign tmp_9_fu_2069_p3 = {{p_Result_125_reg_3352}, {add_ln1124_7_fu_2063_p2}};

assign tmp_V_12_fu_248_p2 = (24'd0 - y_int_reg);

assign tmp_V_14_fu_262_p2 = (24'd0 - x_min_int_reg);

assign tmp_V_16_fu_276_p2 = (24'd0 - y_min_int_reg);

assign tmp_V_18_fu_290_p2 = (24'd0 - x_max_int_reg);

assign tmp_V_20_fu_304_p2 = (24'd0 - y_max_int_reg);

assign tmp_V_22_fu_315_p3 = ((p_Result_110_reg_3297[0:0] == 1'b1) ? tmp_V_reg_3303 : x_read_reg_3291);

assign tmp_V_23_fu_614_p3 = ((p_Result_113_reg_3308[0:0] == 1'b1) ? tmp_V_12_reg_3314 : y_read_reg_3285);

assign tmp_V_24_fu_913_p3 = ((p_Result_116_reg_3319[0:0] == 1'b1) ? tmp_V_14_reg_3325 : x_min_read_reg_3279);

assign tmp_V_25_fu_1212_p3 = ((p_Result_119_reg_3330[0:0] == 1'b1) ? tmp_V_16_reg_3336 : y_min_read_reg_3273);

assign tmp_V_26_fu_1511_p3 = ((p_Result_122_reg_3341[0:0] == 1'b1) ? tmp_V_18_reg_3347 : x_max_read_reg_3267);

assign tmp_V_27_fu_1810_p3 = ((p_Result_125_reg_3352[0:0] == 1'b1) ? tmp_V_20_reg_3358 : y_max_read_reg_3261);

assign tmp_V_fu_234_p2 = (24'd0 - x_int_reg);

assign tmp_fu_2107_p4 = {{bitcast_ln200_fu_2104_p1[30:23]}};

assign tmp_s_fu_574_p3 = {{p_Result_110_reg_3297}, {add_ln1124_fu_568_p2}};

assign trunc_ln1098_3_fu_857_p1 = l_3_fu_641_p3[7:0];

assign trunc_ln1098_4_fu_1156_p1 = l_4_fu_940_p3[7:0];

assign trunc_ln1098_5_fu_1455_p1 = l_5_fu_1239_p3[7:0];

assign trunc_ln1098_6_fu_1754_p1 = l_6_fu_1538_p3[7:0];

assign trunc_ln1098_7_fu_2053_p1 = l_7_fu_1837_p3[7:0];

assign trunc_ln1098_fu_558_p1 = l_fu_342_p3[7:0];

assign trunc_ln1099_2_fu_655_p1 = sub_ln1099_3_fu_649_p2[23:0];

assign trunc_ln1099_3_fu_954_p1 = sub_ln1099_4_fu_948_p2[23:0];

assign trunc_ln1099_4_fu_1253_p1 = sub_ln1099_5_fu_1247_p2[23:0];

assign trunc_ln1099_5_fu_1552_p1 = sub_ln1099_6_fu_1546_p2[23:0];

assign trunc_ln1099_6_fu_1851_p1 = sub_ln1099_7_fu_1845_p2[23:0];

assign trunc_ln1099_fu_356_p1 = sub_ln1099_fu_350_p2[23:0];

assign trunc_ln1102_3_fu_681_p1 = sub_ln1099_3_fu_649_p2[4:0];

assign trunc_ln1102_4_fu_980_p1 = sub_ln1099_4_fu_948_p2[4:0];

assign trunc_ln1102_5_fu_1279_p1 = sub_ln1099_5_fu_1247_p2[4:0];

assign trunc_ln1102_6_fu_1578_p1 = sub_ln1099_6_fu_1546_p2[4:0];

assign trunc_ln1102_7_fu_1877_p1 = sub_ln1099_7_fu_1845_p2[4:0];

assign trunc_ln1102_fu_382_p1 = sub_ln1099_fu_350_p2[4:0];

assign trunc_ln200_1_fu_2165_p1 = bitcast_ln200_1_fu_2152_p1[22:0];

assign trunc_ln200_fu_2117_p1 = bitcast_ln200_fu_2104_p1[22:0];

assign trunc_ln224_2_fu_2242_p1 = bitcast_ln224_1_fu_2229_p1[22:0];

assign trunc_ln224_fu_2213_p1 = bitcast_ln224_fu_2200_p1[22:0];

assign ush_2_fu_2502_p3 = ((isNeg_2_fu_2484_p3[0:0] == 1'b1) ? sext_ln1512_2_fu_2498_p1 : add_ln346_2_fu_2478_p2);

assign ush_fu_2351_p3 = ((isNeg_fu_2333_p3[0:0] == 1'b1) ? sext_ln1512_fu_2347_p1 : add_ln346_fu_2327_p2);

assign val_2_fu_2552_p3 = ((isNeg_2_fu_2484_p3[0:0] == 1'b1) ? zext_ln818_2_fu_2538_p1 : tmp_15_fu_2542_p4);

assign val_fu_2401_p3 = ((isNeg_fu_2333_p3[0:0] == 1'b1) ? zext_ln818_fu_2387_p1 : tmp_14_fu_2391_p4);

assign x_f_fu_601_p3 = ((icmp_ln1090_fu_310_p2[0:0] == 1'b1) ? 32'd0 : bitcast_ln766_fu_597_p1);

assign xmax_f_fu_1797_p3 = ((icmp_ln1090_6_fu_1506_p2[0:0] == 1'b1) ? 32'd0 : bitcast_ln766_5_fu_1793_p1);

assign xmin_f_fu_1199_p3 = ((icmp_ln1090_4_fu_908_p2[0:0] == 1'b1) ? 32'd0 : bitcast_ln766_3_fu_1195_p1);

assign xor_ln1104_3_fu_727_p2 = (tmp_40_fu_719_p3 ^ 1'd1);

assign xor_ln1104_4_fu_1026_p2 = (tmp_44_fu_1018_p3 ^ 1'd1);

assign xor_ln1104_5_fu_1325_p2 = (tmp_48_fu_1317_p3 ^ 1'd1);

assign xor_ln1104_6_fu_1624_p2 = (tmp_52_fu_1616_p3 ^ 1'd1);

assign xor_ln1104_7_fu_1923_p2 = (tmp_56_fu_1915_p3 ^ 1'd1);

assign xor_ln1104_fu_428_p2 = (tmp_36_fu_420_p3 ^ 1'd1);

assign xor_ln95_1_fu_2666_p2 = (zext_ln95_fu_2654_p1 ^ select_ln95_1_fu_2658_p3);

assign xor_ln95_2_fu_2766_p2 = (zext_ln95_1_fu_2754_p1 ^ select_ln95_2_fu_2758_p3);

assign xor_ln95_3_fu_2860_p2 = (zext_ln95_2_fu_2848_p1 ^ select_ln95_3_fu_2852_p3);

assign xor_ln95_4_fu_2954_p2 = (zext_ln95_3_fu_2942_p1 ^ select_ln95_4_fu_2946_p3);

assign xor_ln95_5_fu_3048_p2 = (zext_ln95_4_fu_3036_p1 ^ select_ln95_5_fu_3040_p3);

assign xor_ln95_6_fu_3142_p2 = (zext_ln95_5_fu_3130_p1 ^ select_ln95_6_fu_3134_p3);

assign xor_ln95_7_fu_3236_p2 = (zext_ln95_6_fu_3224_p1 ^ select_ln95_7_fu_3228_p3);

assign xor_ln95_fu_2682_p2 = (zext_ln93_fu_2672_p1 ^ select_ln95_fu_2675_p3);

assign xs_exp_V_2_fu_2446_p4 = {{data_V_2_fu_2430_p3[30:23]}};

assign xs_exp_V_fu_2295_p4 = {{data_V_fu_2279_p3[30:23]}};

assign y_f_fu_900_p3 = ((icmp_ln1090_3_fu_609_p2[0:0] == 1'b1) ? 32'd0 : bitcast_ln766_2_fu_896_p1);

assign ymax_f_fu_2096_p3 = ((icmp_ln1090_7_fu_1805_p2[0:0] == 1'b1) ? 32'd0 : bitcast_ln766_6_fu_2092_p1);

assign ymin_f_fu_1498_p3 = ((icmp_ln1090_5_fu_1207_p2[0:0] == 1'b1) ? 32'd0 : bitcast_ln766_4_fu_1494_p1);

assign zext_ln1102_3_fu_691_p1 = sub_ln1102_3_fu_685_p2;

assign zext_ln1102_4_fu_990_p1 = sub_ln1102_4_fu_984_p2;

assign zext_ln1102_5_fu_1289_p1 = sub_ln1102_5_fu_1283_p2;

assign zext_ln1102_6_fu_1588_p1 = sub_ln1102_6_fu_1582_p2;

assign zext_ln1102_7_fu_1887_p1 = sub_ln1102_7_fu_1881_p2;

assign zext_ln1102_fu_392_p1 = sub_ln1102_fu_386_p2;

assign zext_ln1112_2_fu_767_p1 = tmp_V_23_fu_614_p3;

assign zext_ln1112_3_fu_1066_p1 = tmp_V_24_fu_913_p3;

assign zext_ln1112_4_fu_1365_p1 = tmp_V_25_fu_1212_p3;

assign zext_ln1112_5_fu_1664_p1 = tmp_V_26_fu_1511_p3;

assign zext_ln1112_6_fu_1963_p1 = tmp_V_27_fu_1810_p3;

assign zext_ln1112_fu_468_p1 = tmp_V_22_fu_315_p3;

assign zext_ln1113_2_fu_783_p1 = add_ln1113_2_fu_777_p2;

assign zext_ln1113_3_fu_1082_p1 = add_ln1113_3_fu_1076_p2;

assign zext_ln1113_4_fu_1381_p1 = add_ln1113_4_fu_1375_p2;

assign zext_ln1113_5_fu_1680_p1 = add_ln1113_5_fu_1674_p2;

assign zext_ln1113_6_fu_1979_p1 = add_ln1113_6_fu_1973_p2;

assign zext_ln1113_fu_484_p1 = add_ln1113_fu_478_p2;

assign zext_ln1114_2_fu_799_p1 = sub_ln1114_1_fu_793_p2;

assign zext_ln1114_3_fu_1098_p1 = sub_ln1114_2_fu_1092_p2;

assign zext_ln1114_4_fu_1397_p1 = sub_ln1114_3_fu_1391_p2;

assign zext_ln1114_5_fu_1696_p1 = sub_ln1114_4_fu_1690_p2;

assign zext_ln1114_6_fu_1995_p1 = sub_ln1114_5_fu_1989_p2;

assign zext_ln1114_fu_500_p1 = sub_ln1114_fu_494_p2;

assign zext_ln1116_3_fu_817_p1 = or_ln1104_3_fu_759_p3;

assign zext_ln1116_4_fu_1116_p1 = or_ln1104_4_fu_1058_p3;

assign zext_ln1116_5_fu_1415_p1 = or_ln1104_5_fu_1357_p3;

assign zext_ln1116_6_fu_1714_p1 = or_ln1104_6_fu_1656_p3;

assign zext_ln1116_7_fu_2013_p1 = or_ln1104_7_fu_1955_p3;

assign zext_ln1116_fu_518_p1 = or_ln_fu_460_p3;

assign zext_ln1117_2_fu_837_p1 = m_fu_827_p4;

assign zext_ln1117_3_fu_1136_p1 = m_40_fu_1126_p4;

assign zext_ln1117_4_fu_1435_p1 = m_41_fu_1425_p4;

assign zext_ln1117_5_fu_1734_p1 = m_42_fu_1724_p4;

assign zext_ln1117_6_fu_2033_p1 = m_43_fu_2023_p4;

assign zext_ln1117_fu_538_p1 = m_39_fu_528_p4;

assign zext_ln1488_2_fu_2514_p1 = $unsigned(sext_ln1488_2_fu_2510_p1);

assign zext_ln1488_fu_2363_p1 = $unsigned(sext_ln1488_fu_2359_p1);

assign zext_ln15_2_fu_2470_p1 = mantissa_2_fu_2460_p4;

assign zext_ln15_fu_2319_p1 = mantissa_fu_2309_p4;

assign zext_ln346_2_fu_2474_p1 = xs_exp_V_2_fu_2446_p4;

assign zext_ln346_fu_2323_p1 = xs_exp_V_fu_2295_p4;

assign zext_ln818_2_fu_2538_p1 = tmp_65_fu_2530_p3;

assign zext_ln818_fu_2387_p1 = tmp_61_fu_2379_p3;

assign zext_ln93_fu_2672_p1 = ry_reg_3488;

assign zext_ln95_1_fu_2754_p1 = tmp_73_fu_2746_p3;

assign zext_ln95_2_fu_2848_p1 = tmp_77_fu_2840_p3;

assign zext_ln95_3_fu_2942_p1 = tmp_81_fu_2934_p3;

assign zext_ln95_4_fu_3036_p1 = tmp_85_fu_3028_p3;

assign zext_ln95_5_fu_3130_p1 = tmp_89_fu_3122_p3;

assign zext_ln95_6_fu_3224_p1 = select_ln93_13_fu_3216_p3;

assign zext_ln95_fu_2654_p1 = tmp_69_fu_2646_p3;

endmodule //tri2d_getHilbertCode
