// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tri2d_compactTriangleIndices (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tri_num_V_i,
        tri_num_V_o,
        tri_num_V_o_ap_vld,
        face_used_V_address0,
        face_used_V_ce0,
        face_used_V_we0,
        face_used_V_d0,
        face_used_V_q0,
        face_used_V_address1,
        face_used_V_ce1,
        face_used_V_q1,
        face_edge_V_address0,
        face_edge_V_ce0,
        face_edge_V_we0,
        face_edge_V_d0,
        face_edge_V_q0,
        face_prev_V_address0,
        face_prev_V_ce0,
        face_prev_V_we0,
        face_prev_V_d0,
        face_prev_V_q0,
        face_next_V_address0,
        face_next_V_ce0,
        face_next_V_we0,
        face_next_V_d0,
        face_next_V_q0,
        global_edge_idx_V,
        he_used_V_address0,
        he_used_V_ce0,
        he_used_V_q0,
        he_face_V_address0,
        he_face_V_ce0,
        he_face_V_we0,
        he_face_V_d0,
        he_face_V_address1,
        he_face_V_ce1,
        he_face_V_q1,
        enhanced_grid_total_cells,
        enhanced_grid_flat_cells_triangle_count_address0,
        enhanced_grid_flat_cells_triangle_count_ce0,
        enhanced_grid_flat_cells_triangle_count_we0,
        enhanced_grid_flat_cells_triangle_count_d0,
        enhanced_grid_flat_cells_triangle_count_q0,
        enhanced_grid_flat_cells_triangles_V_address0,
        enhanced_grid_flat_cells_triangles_V_ce0,
        enhanced_grid_flat_cells_triangles_V_we0,
        enhanced_grid_flat_cells_triangles_V_d0,
        enhanced_grid_flat_cells_triangles_V_q0
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [13:0] tri_num_V_i;
output  [13:0] tri_num_V_o;
output   tri_num_V_o_ap_vld;
output  [13:0] face_used_V_address0;
output   face_used_V_ce0;
output   face_used_V_we0;
output  [0:0] face_used_V_d0;
input  [0:0] face_used_V_q0;
output  [13:0] face_used_V_address1;
output   face_used_V_ce1;
input  [0:0] face_used_V_q1;
output  [13:0] face_edge_V_address0;
output   face_edge_V_ce0;
output   face_edge_V_we0;
output  [14:0] face_edge_V_d0;
input  [14:0] face_edge_V_q0;
output  [13:0] face_prev_V_address0;
output   face_prev_V_ce0;
output   face_prev_V_we0;
output  [13:0] face_prev_V_d0;
input  [13:0] face_prev_V_q0;
output  [13:0] face_next_V_address0;
output   face_next_V_ce0;
output   face_next_V_we0;
output  [13:0] face_next_V_d0;
input  [13:0] face_next_V_q0;
input  [14:0] global_edge_idx_V;
output  [15:0] he_used_V_address0;
output   he_used_V_ce0;
input  [0:0] he_used_V_q0;
output  [15:0] he_face_V_address0;
output   he_face_V_ce0;
output   he_face_V_we0;
output  [13:0] he_face_V_d0;
output  [15:0] he_face_V_address1;
output   he_face_V_ce1;
input  [13:0] he_face_V_q1;
input  [12:0] enhanced_grid_total_cells;
output  [11:0] enhanced_grid_flat_cells_triangle_count_address0;
output   enhanced_grid_flat_cells_triangle_count_ce0;
output   enhanced_grid_flat_cells_triangle_count_we0;
output  [31:0] enhanced_grid_flat_cells_triangle_count_d0;
input  [31:0] enhanced_grid_flat_cells_triangle_count_q0;
output  [16:0] enhanced_grid_flat_cells_triangles_V_address0;
output   enhanced_grid_flat_cells_triangles_V_ce0;
output   enhanced_grid_flat_cells_triangles_V_we0;
output  [13:0] enhanced_grid_flat_cells_triangles_V_d0;
input  [13:0] enhanced_grid_flat_cells_triangles_V_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[13:0] tri_num_V_o;
reg tri_num_V_o_ap_vld;
reg[13:0] face_used_V_address0;
reg face_used_V_ce0;
reg face_used_V_we0;
reg face_used_V_ce1;
reg[11:0] enhanced_grid_flat_cells_triangle_count_address0;
reg enhanced_grid_flat_cells_triangle_count_ce0;
reg enhanced_grid_flat_cells_triangle_count_we0;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [13:0] tri_num_V_load_reg_238;
wire    ap_CS_fsm_state3;
wire   [16:0] trunc_ln502_fu_167_p1;
reg   [16:0] trunc_ln502_reg_252;
wire    ap_CS_fsm_state7;
reg   [11:0] enhanced_grid_flat_cells_triangle_count_addr_reg_260;
wire   [0:0] icmp_ln502_fu_177_p2;
reg   [31:0] enhanced_grid_flat_cells_triangle_count_load_reg_265;
wire    ap_CS_fsm_state8;
reg   [13:0] index_map_V_address0;
reg    index_map_V_ce0;
reg    index_map_V_we0;
reg   [13:0] index_map_V_d0;
wire   [13:0] index_map_V_q0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_start;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_done;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_idle;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_ready;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_index_map_V_address0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_index_map_V_ce0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_index_map_V_we0;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_index_map_V_d0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_start;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_done;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_idle;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_ready;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_index_map_V_address0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_index_map_V_ce0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_index_map_V_we0;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_index_map_V_d0;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_new_tri_count_V_out;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_new_tri_count_V_out_ap_vld;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_face_used_V_address0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_face_used_V_ce0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_start;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_done;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_idle;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_ready;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_address0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_ce0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_we0;
wire   [0:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_d0;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_address1;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_ce1;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_edge_V_address0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_edge_V_ce0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_edge_V_we0;
wire   [14:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_edge_V_d0;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_prev_V_address0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_prev_V_ce0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_prev_V_we0;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_prev_V_d0;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_next_V_address0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_next_V_ce0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_next_V_we0;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_next_V_d0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_start;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_done;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_idle;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_ready;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_index_map_V_address0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_index_map_V_ce0;
wire   [15:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_used_V_address0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_used_V_ce0;
wire   [15:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_address0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_ce0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_we0;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_d0;
wire   [15:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_address1;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_ce1;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_start;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_done;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_idle;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_ready;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_index_map_V_address0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_index_map_V_ce0;
wire   [31:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_write_pos_out;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_write_pos_out_ap_vld;
wire   [16:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_enhanced_grid_flat_cells_triangles_V_address0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_enhanced_grid_flat_cells_triangles_V_ce0;
wire    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_enhanced_grid_flat_cells_triangles_V_we0;
wire   [13:0] grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_enhanced_grid_flat_cells_triangles_V_d0;
reg    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_start_reg;
reg    grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_start_reg;
wire    ap_CS_fsm_state9;
wire   [63:0] zext_ln502_fu_188_p1;
reg   [17:0] phi_mul_fu_50;
wire   [17:0] add_ln502_1_fu_171_p2;
reg   [12:0] cell_idx_fu_54;
wire   [12:0] add_ln502_fu_182_p2;
wire    ap_CS_fsm_state10;
reg    ap_block_state6_on_subcall_done;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_start_reg = 1'b0;
#0 grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_start_reg = 1'b0;
#0 grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_start_reg = 1'b0;
#0 grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_start_reg = 1'b0;
#0 grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_start_reg = 1'b0;
end

tri2d_compactTriangleIndices_index_map_V_RAM_AUTO_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 12000 ),
    .AddressWidth( 14 ))
index_map_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(index_map_V_address0),
    .ce0(index_map_V_ce0),
    .we0(index_map_V_we0),
    .d0(index_map_V_d0),
    .q0(index_map_V_q0)
);

tri2d_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1 grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_start),
    .ap_done(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_done),
    .ap_idle(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_idle),
    .ap_ready(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_ready),
    .index_map_V_address0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_index_map_V_address0),
    .index_map_V_ce0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_index_map_V_ce0),
    .index_map_V_we0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_index_map_V_we0),
    .index_map_V_d0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_index_map_V_d0)
);

tri2d_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2 grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_start),
    .ap_done(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_done),
    .ap_idle(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_idle),
    .ap_ready(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_ready),
    .tri_num_V_load(tri_num_V_i),
    .index_map_V_address0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_index_map_V_address0),
    .index_map_V_ce0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_index_map_V_ce0),
    .index_map_V_we0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_index_map_V_we0),
    .index_map_V_d0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_index_map_V_d0),
    .new_tri_count_V_out(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_new_tri_count_V_out),
    .new_tri_count_V_out_ap_vld(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_new_tri_count_V_out_ap_vld),
    .face_used_V_address0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_face_used_V_address0),
    .face_used_V_ce0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_face_used_V_ce0),
    .face_used_V_q0(face_used_V_q0)
);

tri2d_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3 grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_start),
    .ap_done(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_done),
    .ap_idle(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_idle),
    .ap_ready(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_ready),
    .tri_num_V_load(tri_num_V_i),
    .face_used_V_address0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_address0),
    .face_used_V_ce0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_ce0),
    .face_used_V_we0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_we0),
    .face_used_V_d0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_d0),
    .face_used_V_address1(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_address1),
    .face_used_V_ce1(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_ce1),
    .face_used_V_q1(face_used_V_q1),
    .face_edge_V_address0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_edge_V_address0),
    .face_edge_V_ce0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_edge_V_ce0),
    .face_edge_V_we0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_edge_V_we0),
    .face_edge_V_d0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_edge_V_d0),
    .face_edge_V_q0(face_edge_V_q0),
    .face_prev_V_address0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_prev_V_address0),
    .face_prev_V_ce0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_prev_V_ce0),
    .face_prev_V_we0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_prev_V_we0),
    .face_prev_V_d0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_prev_V_d0),
    .face_prev_V_q0(face_prev_V_q0),
    .face_next_V_address0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_next_V_address0),
    .face_next_V_ce0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_next_V_ce0),
    .face_next_V_we0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_next_V_we0),
    .face_next_V_d0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_next_V_d0),
    .face_next_V_q0(face_next_V_q0)
);

tri2d_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4 grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_start),
    .ap_done(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_done),
    .ap_idle(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_idle),
    .ap_ready(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_ready),
    .global_edge_idx_V_load(global_edge_idx_V),
    .tri_num_V_load(tri_num_V_i),
    .index_map_V_address0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_index_map_V_address0),
    .index_map_V_ce0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_index_map_V_ce0),
    .index_map_V_q0(index_map_V_q0),
    .he_used_V_address0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_used_V_address0),
    .he_used_V_ce0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_used_V_ce0),
    .he_used_V_q0(he_used_V_q0),
    .he_face_V_address0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_address0),
    .he_face_V_ce0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_ce0),
    .he_face_V_we0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_we0),
    .he_face_V_d0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_d0),
    .he_face_V_address1(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_address1),
    .he_face_V_ce1(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_ce1),
    .he_face_V_q1(he_face_V_q1)
);

tri2d_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6 grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_start),
    .ap_done(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_done),
    .ap_idle(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_idle),
    .ap_ready(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_ready),
    .enhanced_grid_flat_cells_triangle_count_load(enhanced_grid_flat_cells_triangle_count_load_reg_265),
    .phi_mul(trunc_ln502_reg_252),
    .tri_num_V_load(tri_num_V_load_reg_238),
    .index_map_V_address0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_index_map_V_address0),
    .index_map_V_ce0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_index_map_V_ce0),
    .index_map_V_q0(index_map_V_q0),
    .write_pos_out(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_write_pos_out),
    .write_pos_out_ap_vld(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_write_pos_out_ap_vld),
    .enhanced_grid_flat_cells_triangles_V_address0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_enhanced_grid_flat_cells_triangles_V_address0),
    .enhanced_grid_flat_cells_triangles_V_ce0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_enhanced_grid_flat_cells_triangles_V_ce0),
    .enhanced_grid_flat_cells_triangles_V_we0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_enhanced_grid_flat_cells_triangles_V_we0),
    .enhanced_grid_flat_cells_triangles_V_d0(grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_enhanced_grid_flat_cells_triangles_V_d0),
    .enhanced_grid_flat_cells_triangles_V_q0(enhanced_grid_flat_cells_triangles_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_start_reg <= 1'b1;
        end else if ((grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_ready == 1'b1)) begin
            grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_start_reg <= 1'b1;
        end else if ((grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_ready == 1'b1)) begin
            grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_ready == 1'b1)) begin
            grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_start_reg <= 1'b1;
        end else if ((grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_ready == 1'b1)) begin
            grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_ready == 1'b1)) begin
            grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        cell_idx_fu_54 <= 13'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln502_fu_177_p2 == 1'd0))) begin
        cell_idx_fu_54 <= add_ln502_fu_182_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul_fu_50 <= 18'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln502_fu_177_p2 == 1'd0))) begin
        phi_mul_fu_50 <= add_ln502_1_fu_171_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln502_fu_177_p2 == 1'd0))) begin
        enhanced_grid_flat_cells_triangle_count_addr_reg_260 <= zext_ln502_fu_188_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        enhanced_grid_flat_cells_triangle_count_load_reg_265 <= enhanced_grid_flat_cells_triangle_count_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tri_num_V_load_reg_238 <= tri_num_V_i;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        trunc_ln502_reg_252 <= trunc_ln502_fu_167_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state6_on_subcall_done)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state7) & (icmp_ln502_fu_177_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln502_fu_177_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        enhanced_grid_flat_cells_triangle_count_address0 = enhanced_grid_flat_cells_triangle_count_addr_reg_260;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        enhanced_grid_flat_cells_triangle_count_address0 = zext_ln502_fu_188_p1;
    end else begin
        enhanced_grid_flat_cells_triangle_count_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7))) begin
        enhanced_grid_flat_cells_triangle_count_ce0 = 1'b1;
    end else begin
        enhanced_grid_flat_cells_triangle_count_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        enhanced_grid_flat_cells_triangle_count_we0 = 1'b1;
    end else begin
        enhanced_grid_flat_cells_triangle_count_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        face_used_V_address0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        face_used_V_address0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_face_used_V_address0;
    end else begin
        face_used_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        face_used_V_ce0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        face_used_V_ce0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_face_used_V_ce0;
    end else begin
        face_used_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        face_used_V_ce1 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_ce1;
    end else begin
        face_used_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        face_used_V_we0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_we0;
    end else begin
        face_used_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        index_map_V_address0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_index_map_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        index_map_V_address0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_index_map_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        index_map_V_address0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_index_map_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        index_map_V_address0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_index_map_V_address0;
    end else begin
        index_map_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        index_map_V_ce0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_index_map_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        index_map_V_ce0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_index_map_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        index_map_V_ce0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_index_map_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        index_map_V_ce0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_index_map_V_ce0;
    end else begin
        index_map_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        index_map_V_d0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_index_map_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        index_map_V_d0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_index_map_V_d0;
    end else begin
        index_map_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        index_map_V_we0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_index_map_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        index_map_V_we0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_index_map_V_we0;
    end else begin
        index_map_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln502_fu_177_p2 == 1'd1))) begin
        tri_num_V_o = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_new_tri_count_V_out;
    end else begin
        tri_num_V_o = tri_num_V_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln502_fu_177_p2 == 1'd1))) begin
        tri_num_V_o_ap_vld = 1'b1;
    end else begin
        tri_num_V_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln502_fu_177_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln502_1_fu_171_p2 = (phi_mul_fu_50 + 18'd25);

assign add_ln502_fu_182_p2 = (cell_idx_fu_54 + 13'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state6_on_subcall_done = ((grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_done == 1'b0) | (grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_done == 1'b0));
end

assign enhanced_grid_flat_cells_triangle_count_d0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_write_pos_out;

assign enhanced_grid_flat_cells_triangles_V_address0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_enhanced_grid_flat_cells_triangles_V_address0;

assign enhanced_grid_flat_cells_triangles_V_ce0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_enhanced_grid_flat_cells_triangles_V_ce0;

assign enhanced_grid_flat_cells_triangles_V_d0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_enhanced_grid_flat_cells_triangles_V_d0;

assign enhanced_grid_flat_cells_triangles_V_we0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_enhanced_grid_flat_cells_triangles_V_we0;

assign face_edge_V_address0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_edge_V_address0;

assign face_edge_V_ce0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_edge_V_ce0;

assign face_edge_V_d0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_edge_V_d0;

assign face_edge_V_we0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_edge_V_we0;

assign face_next_V_address0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_next_V_address0;

assign face_next_V_ce0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_next_V_ce0;

assign face_next_V_d0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_next_V_d0;

assign face_next_V_we0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_next_V_we0;

assign face_prev_V_address0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_prev_V_address0;

assign face_prev_V_ce0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_prev_V_ce0;

assign face_prev_V_d0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_prev_V_d0;

assign face_prev_V_we0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_prev_V_we0;

assign face_used_V_address1 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_address1;

assign face_used_V_d0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_face_used_V_d0;

assign grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_start = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_466_1_fu_83_ap_start_reg;

assign grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_start = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_471_2_fu_89_ap_start_reg;

assign grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_start = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_479_3_fu_98_ap_start_reg;

assign grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_start = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_ap_start_reg;

assign grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_start = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_506_6_fu_122_ap_start_reg;

assign he_face_V_address0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_address0;

assign he_face_V_address1 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_address1;

assign he_face_V_ce0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_ce0;

assign he_face_V_ce1 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_ce1;

assign he_face_V_d0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_d0;

assign he_face_V_we0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_face_V_we0;

assign he_used_V_address0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_used_V_address0;

assign he_used_V_ce0 = grp_compactTriangleIndices_Pipeline_VITIS_LOOP_490_4_fu_111_he_used_V_ce0;

assign icmp_ln502_fu_177_p2 = ((cell_idx_fu_54 == enhanced_grid_total_cells) ? 1'b1 : 1'b0);

assign trunc_ln502_fu_167_p1 = phi_mul_fu_50[16:0];

assign zext_ln502_fu_188_p1 = cell_idx_fu_54;

endmodule //tri2d_compactTriangleIndices
